import const_proto_weapon

PROTOS_WEAPON_SIMPLE_MELEE_LIGHT_MASTERWORK = [\
	const_proto_weapon.PROTO_WEAPON_DAGGER_MASTERWORK \
	, const_proto_weapon.PROTO_WEAPON_DAGGER_THROWING_MASTERWORK \
	, const_proto_weapon.PROTO_WEAPON_MACE_LIGHT_MASTERWORK \
	, const_proto_weapon.PROTO_WEAPON_SICKLE_MASTERWORK \
	]

PROTOS_WEAPON_SIMPLE_MELEE_ONE_HANDED_MASTERWORK = [\
	const_proto_weapon.PROTO_WEAPON_CLUB_MASTERWORK \
	, const_proto_weapon.PROTO_WEAPON_MACE_HEAVY_MASTERWORK \
	, const_proto_weapon.PROTO_WEAPON_MORNINGSTAR_MASTERWORK \
	, const_proto_weapon.PROTO_WEAPON_SHORTSPEAR_MASTERWORK \
	]

PROTOS_WEAPON_SIMPLE_MELEE_TWO_HANDED_MASTERWORK = [\
	const_proto_weapon.PROTO_WEAPON_LONGSPEAR_MASTERWORK \
	, const_proto_weapon.PROTO_WEAPON_QUARTERSTAFF_MASTERWORK \
	, const_proto_weapon.PROTO_WEAPON_SPEAR_MASTERWORK \
	]

PROTOS_WEAPON_SIMPLE_MELEE_MASTERWORK = PROTOS_WEAPON_SIMPLE_MELEE_LIGHT_MASTERWORK + PROTOS_WEAPON_SIMPLE_MELEE_ONE_HANDED_MASTERWORK + PROTOS_WEAPON_SIMPLE_MELEE_TWO_HANDED_MASTERWORK

PROTOS_WEAPON_SIMPLE_RANGED_MASTERWORK = [\
	const_proto_weapon.PROTO_WEAPON_CROSSBOW_HEAVY_MASTERWORK \
	, const_proto_weapon.PROTO_WEAPON_CROSSBOW_LIGHT_MASTERWORK \
	, const_proto_weapon.PROTO_AMMO_BOLT_QUIVER \
	, const_proto_weapon.PROTO_WEAPON_JAVELIN_MASTERWORK \
	, const_proto_weapon.PROTO_WEAPON_DART_MASTERWORK \
	, const_proto_weapon.PROTO_WEAPON_SLING_MASTERWORK \
	, const_proto_weapon.PROTO_AMMO_BULLET_POUCH \
	]

PROTOS_WEAPON_SIMPLE_MASTERWORK = PROTOS_WEAPON_SIMPLE_MELEE_MASTERWORK + PROTOS_WEAPON_SIMPLE_RANGED_MASTERWORK

PROTOS_WEAPON_MARTIAL_MELEE_LIGHT_MASTERWORK = [\
	const_proto_weapon.PROTO_WEAPON_HAMMER_LIGHT_MASTERWORK \
	, const_proto_weapon.PROTO_WEAPON_HANDAXE_MASTERWORK \
	, const_proto_weapon.PROTO_WEAPON_KUKRI_MASTERWORK \
	, const_proto_weapon.PROTO_WEAPON_SICKLE_MASTERWORK \
	, const_proto_weapon.PROTO_WEAPON_SHORTSWORD_MASTERWORK \
	] # missing: Throwing Axe, Light Pick, Sap

PROTOS_WEAPON_MARTIAL_MELEE_ONE_HANDED_MASTERWORK = [\
	const_proto_weapon.PROTO_BATTLEAXE_MASTERWORK \
	, const_proto_weapon.PROTO_FLAIL_MASTERWORK \
	, const_proto_weapon.PROTO_LONGSWORD_MASTERWORK \
	, const_proto_weapon.PROTO_WEAPON_PICK_HEAVY_MASTERWORK \
	, const_proto_weapon.PROTO_RAPIER_MASTERWORK \
	, const_proto_weapon.PROTO_SCIMITAR_MASTERWORK \
	, const_proto_weapon.PROTO_WEAPON_TRIDENT_MASTERWORK \
	, const_proto_weapon.PROTO_WEAPON_WARHAMMER_MASTERWORK \
	]

PROTOS_WEAPON_MARTIAL_MELEE_TWO_HANDED_MASTERWORK = [\
	const_proto_weapon.PROTO_WEAPON_FALCHION_MASTERWORK \
	, const_proto_weapon.PROTO_WEAPON_GLAIVE_MASTERWORK \
	, const_proto_weapon.PROTO_WEAPON_GREATAXE_MASTERWORK \
	, const_proto_weapon.PROTO_WEAPON_GREATCLUB_MASTERWORK \
	, const_proto_weapon.PROTO_WEAPON_FLAIL_HEAVY_MASTERWORK \
	, const_proto_weapon.PROTO_WEAPON_GREATSWORD_MASTERWORK \
	, const_proto_weapon.PROTO_WEAPON_GUISARME_MASTERWORK \
	, const_proto_weapon.PROTO_WEAPON_HALBERD_MASTERWORK \
	, const_proto_weapon.PROTO_WEAPON_RANSEUR_MASTERWORK \
	, const_proto_weapon.PROTO_WEAPON_SCYTHE_MASTERWORK \
	] # missing: Lance

PROTOS_WEAPON_MARTIAL_MELEE_MASTERWORK = PROTOS_WEAPON_MARTIAL_MELEE_LIGHT_MASTERWORK + PROTOS_WEAPON_MARTIAL_MELEE_ONE_HANDED_MASTERWORK + PROTOS_WEAPON_MARTIAL_MELEE_TWO_HANDED_MASTERWORK

PROTOS_WEAPON_MARTIAL_RANGED_MASTERWORK = [\
	const_proto_weapon.PROTO_WEAPON_LONGBOW_MASTERWORK \
	, const_proto_weapon.PROTO_WEAPON_LONGBOW_COMPOSITE_12_MASTERWORK \
	, const_proto_weapon.PROTO_WEAPON_LONGBOW_COMPOSITE_14_MASTERWORK \
	, const_proto_weapon.PROTO_WEAPON_LONGBOW_COMPOSITE_16_MASTERWORK \
	, const_proto_weapon.PROTO_WEAPON_SHORTBOW_MASTERWORK \
	, const_proto_weapon.PROTO_AMMO_ARROW_QUIVER \
	] # missing: Shortbow Composite

PROTOS_WEAPON_MARTIAL_MASTERWORK = PROTOS_WEAPON_MARTIAL_MELEE_MASTERWORK + PROTOS_WEAPON_MARTIAL_RANGED_MASTERWORK

PROTOS_WEAPON_EXOTIC_MELEE_LIGHT_MASTERWORK = [\
	const_proto_weapon.PROTO_WEAPON_SPIKED_KAMA_MASTERWORK \
	, const_proto_weapon.PROTO_WEAPON_SPIKED_SIANGHAM_MASTERWORK \
	] # missing: Nunchaku, Sai

PROTOS_WEAPON_EXOTIC_MELEE_ONE_HANDED_MASTERWORK = [\
	const_proto_weapon.PROTO_WEAPON_SWORD_BASTARD_MASTERWORK \
	, const_proto_weapon.PROTO_WEAPON_WARAXE_DWARVEN_MASTERWORK \
	] # missing: Whip

PROTOS_WEAPON_EXOTIC_MELEE_TWO_HANDED_MASTERWORK = [\
	const_proto_weapon.PROTO_WEAPON_DOUBLEAXE_ORC_MASTERWORK \
	, const_proto_weapon.PROTO_WEAPON_SPIKED_CHAIN_MASTERWORK \
	, const_proto_weapon.PROTO_WEAPON_HAMMER_GNOME_HOOKED_MASTERWORK \
	] # missing: Dire Flail, Two-bladed Sword, Urgrosh

PROTOS_WEAPON_EXOTIC_MELEE_MASTERWORK = PROTOS_WEAPON_EXOTIC_MELEE_LIGHT_MASTERWORK + PROTOS_WEAPON_EXOTIC_MELEE_ONE_HANDED_MASTERWORK + PROTOS_WEAPON_EXOTIC_MELEE_TWO_HANDED_MASTERWORK

PROTOS_WEAPON_EXOTIC_RANGED_MASTERWORK = [\
	const_proto_weapon.PROTO_WEAPON_CROSSBOW_REPEATING_LIGHT_MASTERWORK \
	, const_proto_weapon.PROTO_WEAPON_SHURIKEN_MASTERWORK \
	] # missing: Bolas, Hand Crossbow, Repeating Heavy Crossbow, Net

PROTOS_WEAPON_EXOTIC_MASTERWORK = PROTOS_WEAPON_EXOTIC_MELEE_MASTERWORK + PROTOS_WEAPON_EXOTIC_RANGED_MASTERWORK