import const_proto_wands

PROTOS_WANDS_ARCANE_LEVEL_0_ABJURATION = [ \
	 const_proto_wands.PROTO_WAND_OF_RESISTANCE\
	, ]

PROTOS_WANDS_ARCANE_LEVEL_0_CONJURATION = [ \
	 const_proto_wands.PROTO_WAND_OF_ACID_SPLASH\
	, ]

PROTOS_WANDS_ARCANE_LEVEL_0_DIVINATION = [ \
	 const_proto_wands.PROTO_WAND_OF_DETECT_MAGIC \
	, const_proto_wands.PROTO_WAND_OF_READ_MAGIC\
	, ]

PROTOS_WANDS_ARCANE_LEVEL_0_ENCHANTMENT = [ \
	 const_proto_wands.PROTO_WAND_OF_DAZE\
	, ]

PROTOS_WANDS_ARCANE_LEVEL_0_EVOCATION = [ \
	 const_proto_wands.PROTO_WAND_OF_FLARE \
	, const_proto_wands.PROTO_WAND_OF_RAY_OF_FROST\
	, ]

PROTOS_WANDS_ARCANE_LEVEL_0_ILLUSION = []

PROTOS_WANDS_ARCANE_LEVEL_0_NECROMANCY = [ \
	 const_proto_wands.PROTO_WAND_OF_DISRUPT_UNDEAD\
	, ]

PROTOS_WANDS_ARCANE_LEVEL_0_TRANSMUTATION = [ \
	 const_proto_wands.PROTO_WAND_OF_OPEN_CLOSE\
	, ]

PROTOS_WANDS_ARCANE_LEVEL_0 =  \
	 PROTOS_WANDS_ARCANE_LEVEL_0_ABJURATION \
	+ PROTOS_WANDS_ARCANE_LEVEL_0_CONJURATION \
	+ PROTOS_WANDS_ARCANE_LEVEL_0_DIVINATION \
	+ PROTOS_WANDS_ARCANE_LEVEL_0_ENCHANTMENT \
	+ PROTOS_WANDS_ARCANE_LEVEL_0_EVOCATION \
	+ PROTOS_WANDS_ARCANE_LEVEL_0_ILLUSION \
	+ PROTOS_WANDS_ARCANE_LEVEL_0_NECROMANCY \
	+ PROTOS_WANDS_ARCANE_LEVEL_0_TRANSMUTATION

PROTOS_WANDS_DIVINE_LEVEL_0_ABJURATION = []

PROTOS_WANDS_DIVINE_LEVEL_0_CONJURATION = [ \
	 const_proto_wands.PROTO_WAND_OF_CURE_MINOR_WOUNDS\
	, ]

PROTOS_WANDS_DIVINE_LEVEL_0_DIVINATION = [ \
	 const_proto_wands.PROTO_WAND_OF_GUIDANCE\
	, ]

PROTOS_WANDS_DIVINE_LEVEL_0_ENCHANTMENT = []

PROTOS_WANDS_DIVINE_LEVEL_0_EVOCATION = []

PROTOS_WANDS_DIVINE_LEVEL_0_ILLUSION = []

PROTOS_WANDS_DIVINE_LEVEL_0_NECROMANCY = [ \
	 const_proto_wands.PROTO_WAND_OF_INFLICT_MINOR_WOUNDS\
	, ]

PROTOS_WANDS_DIVINE_LEVEL_0_TRANSMUTATION = [ \
	 const_proto_wands.PROTO_WAND_OF_VIRTUE\
	, ]

PROTOS_WANDS_DIVINE_LEVEL_0 =  \
	 PROTOS_WANDS_DIVINE_LEVEL_0_ABJURATION \
	+ PROTOS_WANDS_DIVINE_LEVEL_0_CONJURATION \
	+ PROTOS_WANDS_DIVINE_LEVEL_0_DIVINATION \
	+ PROTOS_WANDS_DIVINE_LEVEL_0_ENCHANTMENT \
	+ PROTOS_WANDS_DIVINE_LEVEL_0_EVOCATION \
	+ PROTOS_WANDS_DIVINE_LEVEL_0_ILLUSION \
	+ PROTOS_WANDS_DIVINE_LEVEL_0_NECROMANCY \
	+ PROTOS_WANDS_DIVINE_LEVEL_0_TRANSMUTATION

PROTOS_WANDS_ARCANE_LEVEL_1_ABJURATION = [ \
	 const_proto_wands.PROTO_WAND_OF_ENDURE_ELEMENTS \
	, const_proto_wands.PROTO_WAND_OF_PROTECTION_FROM_CHAOS \
	, const_proto_wands.PROTO_WAND_OF_PROTECTION_FROM_GOOD \
	, const_proto_wands.PROTO_WAND_OF_PROTECTION_FROM_LAW \
	, const_proto_wands.PROTO_WAND_OF_REMOVE_FEAR \
	, const_proto_wands.PROTO_WAND_OF_SHIELD\
	, ]

PROTOS_WANDS_ARCANE_LEVEL_1_CONJURATION = [ \
	 const_proto_wands.PROTO_WAND_OF_GREASE \
	, const_proto_wands.PROTO_WAND_OF_MAGE_ARMOR \
	, const_proto_wands.PROTO_WAND_OF_OBSCURING_MIST \
	, const_proto_wands.PROTO_WAND_OF_SUMMON_MONSTER_I\
	, ]

PROTOS_WANDS_ARCANE_LEVEL_1_DIVINATION = [ \
	 const_proto_wands.PROTO_WAND_OF_DETECT_SECRET_DOORS \
	, const_proto_wands.PROTO_WAND_OF_DETECT_UNDEAD \
	, const_proto_wands.PROTO_WAND_OF_IDENTIFY \
	, const_proto_wands.PROTO_WAND_OF_TRUE_STRIKE\
	, ]

PROTOS_WANDS_ARCANE_LEVEL_1_ENCHANTMENT = [ \
	 const_proto_wands.PROTO_WAND_OF_CHARM_PERSON \
	, const_proto_wands.PROTO_WAND_OF_CONFUSION_LESSER \
	, const_proto_wands.PROTO_WAND_OF_SLEEP\
	, ]

PROTOS_WANDS_ARCANE_LEVEL_1_EVOCATION = [ \
	 const_proto_wands.PROTO_WAND_OF_BURNING_HANDS \
	, const_proto_wands.PROTO_WAND_OF_MAGIC_MISSILES_5TH \
	, const_proto_wands.PROTO_WAND_OF_MAGIC_MISSILES_2ND \
	, const_proto_wands.PROTO_WAND_OF_MAGIC_MISSILES_3RD \
	, const_proto_wands.PROTO_WAND_OF_MAGIC_MISSILES_1ST \
	, const_proto_wands.PROTO_WAND_OF_MAGIC_MISSILES_4TH \
	, const_proto_wands.PROTO_WAND_OF_SHOCKING_GRASP\
	, ]

PROTOS_WANDS_ARCANE_LEVEL_1_ILLUSION = [ \
	 const_proto_wands.PROTO_WAND_OF_COLOR_SPRAY\
	, ]

PROTOS_WANDS_ARCANE_LEVEL_1_NECROMANCY = [ \
	 const_proto_wands.PROTO_WAND_OF_CAUSE_FEAR \
	, const_proto_wands.PROTO_WAND_OF_CHILL_TOUCH \
	, const_proto_wands.PROTO_WAND_OF_RAY_OF_ENFEEBLEMENT\
	, ]

PROTOS_WANDS_ARCANE_LEVEL_1_TRANSMUTATION = [ \
	 const_proto_wands.PROTO_WAND_OF_ENLARGE_PERSON \
	, const_proto_wands.PROTO_WAND_OF_ENLARGE_PERSON_USED \
	, const_proto_wands.PROTO_WAND_OF_EXPEDITIOUS_RETREAT \
	, const_proto_wands.PROTO_WAND_OF_MAGIC_WEAPON \
	, const_proto_wands.PROTO_WAND_OF_RAY_OF_CLUMSINESS \
	, const_proto_wands.PROTO_WAND_OF_REDUCE_PERSON\
	, ]

PROTOS_WANDS_ARCANE_LEVEL_1 =  \
	 PROTOS_WANDS_ARCANE_LEVEL_1_ABJURATION \
	+ PROTOS_WANDS_ARCANE_LEVEL_1_CONJURATION \
	+ PROTOS_WANDS_ARCANE_LEVEL_1_DIVINATION \
	+ PROTOS_WANDS_ARCANE_LEVEL_1_ENCHANTMENT \
	+ PROTOS_WANDS_ARCANE_LEVEL_1_EVOCATION \
	+ PROTOS_WANDS_ARCANE_LEVEL_1_ILLUSION \
	+ PROTOS_WANDS_ARCANE_LEVEL_1_NECROMANCY \
	+ PROTOS_WANDS_ARCANE_LEVEL_1_TRANSMUTATION

PROTOS_WANDS_DIVINE_LEVEL_1_ABJURATION = [ \
	 const_proto_wands.PROTO_WAND_OF_ENTROPIC_SHIELD \
	, const_proto_wands.PROTO_WAND_OF_PROTECTION_FROM_EVIL \
	, const_proto_wands.PROTO_WAND_OF_SANCTUARY \
	, const_proto_wands.PROTO_WAND_OF_SHIELD_OF_FAITH\
	, ]

PROTOS_WANDS_DIVINE_LEVEL_1_CONJURATION = [ \
	 const_proto_wands.PROTO_WAND_OF_CURE_LIGHT_WOUNDS \
	, const_proto_wands.PROTO_WAND_OF_SUMMON_NATURES_ALLY_I\
	, ]

PROTOS_WANDS_DIVINE_LEVEL_1_DIVINATION = [ \
	 const_proto_wands.PROTO_WAND_OF_DETECT_CHAOS \
	, const_proto_wands.PROTO_WAND_OF_DETECT_EVIL \
	, const_proto_wands.PROTO_WAND_OF_DETECT_GOOD \
	, const_proto_wands.PROTO_WAND_OF_DETECT_LAW\
	, ]

PROTOS_WANDS_DIVINE_LEVEL_1_ENCHANTMENT = [ \
	 const_proto_wands.PROTO_WAND_OF_BANE \
	, const_proto_wands.PROTO_WAND_OF_BLESS \
	, const_proto_wands.PROTO_WAND_OF_CALM_ANIMALS \
	, const_proto_wands.PROTO_WAND_OF_CHARM_ANIMAL \
	, const_proto_wands.PROTO_WAND_OF_COMMAND\
	, ]

PROTOS_WANDS_DIVINE_LEVEL_1_EVOCATION = [ \
	 const_proto_wands.PROTO_WAND_OF_DIVINE_FAVOR \
	, const_proto_wands.PROTO_WAND_OF_FAERIE_FIRE \
	, const_proto_wands.PROTO_WAND_OF_PRODUCE_FLAME\
	, ]

PROTOS_WANDS_DIVINE_LEVEL_1_ILLUSION = []

PROTOS_WANDS_DIVINE_LEVEL_1_NECROMANCY = [ \
	 const_proto_wands.PROTO_WAND_OF_DOOM \
	, const_proto_wands.PROTO_WAND_OF_INFLICT_LIGHT_WOUNDS\
	, ]

PROTOS_WANDS_DIVINE_LEVEL_1_TRANSMUTATION = [ \
	 const_proto_wands.PROTO_WAND_OF_BLESS_WATER \
	, const_proto_wands.PROTO_WAND_OF_CURSE_WATER \
	, const_proto_wands.PROTO_WAND_OF_ENTANGLE \
	, const_proto_wands.PROTO_WAND_OF_GOODBERRY \
	, const_proto_wands.PROTO_WAND_OF_LONGSTRIDER \
	, const_proto_wands.PROTO_WAND_OF_MAGIC_FANG \
	, const_proto_wands.PROTO_WAND_OF_MAGIC_STONE \
	, const_proto_wands.PROTO_WAND_OF_SHILLELAGH\
	, ]

PROTOS_WANDS_DIVINE_LEVEL_1 =  \
	 PROTOS_WANDS_DIVINE_LEVEL_1_ABJURATION \
	+ PROTOS_WANDS_DIVINE_LEVEL_1_CONJURATION \
	+ PROTOS_WANDS_DIVINE_LEVEL_1_DIVINATION \
	+ PROTOS_WANDS_DIVINE_LEVEL_1_ENCHANTMENT \
	+ PROTOS_WANDS_DIVINE_LEVEL_1_EVOCATION \
	+ PROTOS_WANDS_DIVINE_LEVEL_1_ILLUSION \
	+ PROTOS_WANDS_DIVINE_LEVEL_1_NECROMANCY \
	+ PROTOS_WANDS_DIVINE_LEVEL_1_TRANSMUTATION

PROTOS_WANDS_ARCANE_LEVEL_2_ABJURATION = [ \
	 const_proto_wands.PROTO_WAND_OF_PROTECTION_FROM_ARROWS \
	, const_proto_wands.PROTO_WAND_OF_RESIST_ENERGY\
	, ]

PROTOS_WANDS_ARCANE_LEVEL_2_CONJURATION = [ \
	 const_proto_wands.PROTO_WAND_OF_FOG_CLOUD \
	, const_proto_wands.PROTO_WAND_OF_GLITTERDUST \
	, const_proto_wands.PROTO_WAND_OF_GLITTERDUST_USED \
	, const_proto_wands.PROTO_WAND_OF_MELFS_ACID_ARROW \
	, const_proto_wands.PROTO_WAND_OF_SUMMON_MONSTER_II \
	, const_proto_wands.PROTO_WAND_OF_WEB\
	, ]

PROTOS_WANDS_ARCANE_LEVEL_2_DIVINATION = [ \
	 const_proto_wands.PROTO_WAND_OF_SEE_INVISIBILITY\
	, ]

PROTOS_WANDS_ARCANE_LEVEL_2_ENCHANTMENT = [ \
	 const_proto_wands.PROTO_WAND_OF_ANIMAL_TRANCE \
	, const_proto_wands.PROTO_WAND_OF_CALM_EMOTIONS \
	, const_proto_wands.PROTO_WAND_OF_DAZE_MONSTER \
	, const_proto_wands.PROTO_WAND_OF_TASHAS_HIDEOUS_LAUGHTER\
	, ]

PROTOS_WANDS_ARCANE_LEVEL_2_EVOCATION = [ \
	 const_proto_wands.PROTO_WAND_OF_GUST_OF_WIND \
	, const_proto_wands.PROTO_WAND_OF_SCORCHING_RAY_1ST \
	, const_proto_wands.PROTO_WAND_OF_SCORCHING_RAY_1ST_USED \
	, const_proto_wands.PROTO_WAND_OF_SCORCHING_RAY_2ND \
	, const_proto_wands.PROTO_WAND_OF_SCORCHING_RAY_3RD \
	, const_proto_wands.PROTO_WAND_OF_SHATTER \
	, const_proto_wands.PROTO_WAND_OF_SOUND_BURST\
	, ]

PROTOS_WANDS_ARCANE_LEVEL_2_ILLUSION = [ \
	 const_proto_wands.PROTO_WAND_OF_BLUR \
	, const_proto_wands.PROTO_WAND_OF_INVISIBILITY \
	, const_proto_wands.PROTO_WAND_OF_HIDE_FROM_ANIMALS \
	, const_proto_wands.PROTO_WAND_OF_HIDE_FROM_UNDEAD \
	, const_proto_wands.PROTO_WAND_OF_MIRROR_IMAGE \
	, const_proto_wands.PROTO_WAND_OF_SILENCE\
	, ]

PROTOS_WANDS_ARCANE_LEVEL_2_NECROMANCY = [ \
	 const_proto_wands.PROTO_WAND_OF_BLINDNESS_DEAFNESS \
	, const_proto_wands.PROTO_WAND_OF_FALSE_LIFE \
	, const_proto_wands.PROTO_WAND_OF_GHOUL_TOUCH \
	, const_proto_wands.PROTO_WAND_OF_SCARE\
	, ]

PROTOS_WANDS_ARCANE_LEVEL_2_TRANSMUTATION = [ \
	 const_proto_wands.PROTO_WAND_OF_BEARS_ENDURANCE \
	, const_proto_wands.PROTO_WAND_OF_CATS_GRACE \
	, const_proto_wands.PROTO_WAND_OF_EAGLES_SPLENDOR \
	, const_proto_wands.PROTO_WAND_OF_FOXS_CUNNING \
	, const_proto_wands.PROTO_WAND_OF_KNOCK\
	, ]

PROTOS_WANDS_ARCANE_LEVEL_2 =  \
	 PROTOS_WANDS_ARCANE_LEVEL_2_ABJURATION \
	+ PROTOS_WANDS_ARCANE_LEVEL_2_CONJURATION \
	+ PROTOS_WANDS_ARCANE_LEVEL_2_DIVINATION \
	+ PROTOS_WANDS_ARCANE_LEVEL_2_ENCHANTMENT \
	+ PROTOS_WANDS_ARCANE_LEVEL_2_EVOCATION \
	+ PROTOS_WANDS_ARCANE_LEVEL_2_ILLUSION \
	+ PROTOS_WANDS_ARCANE_LEVEL_2_NECROMANCY \
	+ PROTOS_WANDS_ARCANE_LEVEL_2_TRANSMUTATION

PROTOS_WANDS_DIVINE_LEVEL_2_ABJURATION = []

PROTOS_WANDS_DIVINE_LEVEL_2_CONJURATION = [ \
	 const_proto_wands.PROTO_WAND_OF_CURE_MODERATE_WOUNDS \
	, const_proto_wands.PROTO_WAND_OF_DELAY_POISON \
	, const_proto_wands.PROTO_WAND_OF_RESTORATION_LESSER \
	, const_proto_wands.PROTO_WAND_OF_REMOVE_PARALYSIS \
	, const_proto_wands.PROTO_WAND_OF_SUMMON_NATURES_ALLY_II\
	, ]

PROTOS_WANDS_DIVINE_LEVEL_2_DIVINATION = [ \
	 const_proto_wands.PROTO_WAND_OF_FIND_TRAPS\
	, ]

PROTOS_WANDS_DIVINE_LEVEL_2_ENCHANTMENT = [ \
	 const_proto_wands.PROTO_WAND_OF_AID \
	, const_proto_wands.PROTO_WAND_OF_HOLD_ANIMAL\
	, ]

PROTOS_WANDS_DIVINE_LEVEL_2_EVOCATION = [ \
	 const_proto_wands.PROTO_WAND_OF_CONSECRATE \
	, const_proto_wands.PROTO_WAND_OF_DESECRATE \
	, const_proto_wands.PROTO_WAND_OF_SPIRITUAL_WEAPON\
	, ]

PROTOS_WANDS_DIVINE_LEVEL_2_ILLUSION = []

PROTOS_WANDS_DIVINE_LEVEL_2_NECROMANCY = [ \
	 const_proto_wands.PROTO_WAND_OF_DEATH_KNELL \
	, const_proto_wands.PROTO_WAND_OF_INFLICT_MODERATE_WOUNDS\
	, ]

PROTOS_WANDS_DIVINE_LEVEL_2_TRANSMUTATION = [ \
	 const_proto_wands.PROTO_WAND_OF_BARKSKIN \
	, const_proto_wands.PROTO_WAND_OF_BULLS_STRENGTH \
	, const_proto_wands.PROTO_WAND_OF_CHILL_METAL \
	, const_proto_wands.PROTO_WAND_OF_HEAT_METAL \
	, const_proto_wands.PROTO_WAND_OF_OWLS_WISDOM \
	, const_proto_wands.PROTO_WAND_OF_REDUCE_ANIMAL \
	, const_proto_wands.PROTO_WAND_OF_SOFTEN_EARTH_AND_STONE \
	, const_proto_wands.PROTO_WAND_OF_SPIKE_GROWTH \
	, const_proto_wands.PROTO_WAND_OF_TREE_SHAPE\
	, ]

PROTOS_WANDS_DIVINE_LEVEL_2 =  \
	 PROTOS_WANDS_DIVINE_LEVEL_2_ABJURATION \
	+ PROTOS_WANDS_DIVINE_LEVEL_2_CONJURATION \
	+ PROTOS_WANDS_DIVINE_LEVEL_2_DIVINATION \
	+ PROTOS_WANDS_DIVINE_LEVEL_2_ENCHANTMENT \
	+ PROTOS_WANDS_DIVINE_LEVEL_2_EVOCATION \
	+ PROTOS_WANDS_DIVINE_LEVEL_2_ILLUSION \
	+ PROTOS_WANDS_DIVINE_LEVEL_2_NECROMANCY \
	+ PROTOS_WANDS_DIVINE_LEVEL_2_TRANSMUTATION

PROTOS_WANDS_ARCANE_LEVEL_3_ABJURATION = [ \
	 const_proto_wands.PROTO_WAND_OF_DISPEL_MAGIC \
	, const_proto_wands.PROTO_WAND_OF_MAGIC_CIRCLE_AGAINST_CHAOS \
	, const_proto_wands.PROTO_WAND_OF_MAGIC_CIRCLE_AGAINST_EVIL \
	, const_proto_wands.PROTO_WAND_OF_MAGIC_CIRCLE_AGAINST_GOOD \
	, const_proto_wands.PROTO_WAND_OF_MAGIC_CIRCLE_AGAINST_LAW\
	, ]

PROTOS_WANDS_ARCANE_LEVEL_3_CONJURATION = [ \
	 const_proto_wands.PROTO_WAND_OF_SLEET_STORM \
	, const_proto_wands.PROTO_WAND_OF_STINKING_CLOUD \
	, const_proto_wands.PROTO_WAND_OF_SUMMON_MONSTER_III\
	, ]

PROTOS_WANDS_ARCANE_LEVEL_3_DIVINATION = [ \
	 const_proto_wands.PROTO_WAND_OF_CLAIRAUDIENCE_CLAIRVOYANCE\
	, ]

PROTOS_WANDS_ARCANE_LEVEL_3_ENCHANTMENT = [ \
	 const_proto_wands.PROTO_WAND_OF_DEEP_SLUMBER \
	, const_proto_wands.PROTO_WAND_OF_GOOD_HOPE \
	, const_proto_wands.PROTO_WAND_OF_HEROISM \
	, const_proto_wands.PROTO_WAND_OF_HOLD_PERSON \
	, const_proto_wands.PROTO_WAND_OF_RAGE\
	, ]

PROTOS_WANDS_ARCANE_LEVEL_3_EVOCATION = [ \
	 const_proto_wands.PROTO_WAND_OF_FIREBALL_5TH \
	, const_proto_wands.PROTO_WAND_OF_FIREBALL \
	, const_proto_wands.PROTO_WAND_OF_FIREBALL_7TH \
	, const_proto_wands.PROTO_WAND_OF_FIREBALL_9TH \
	, const_proto_wands.PROTO_WAND_OF_FIREBALL_10TH \
	, const_proto_wands.PROTO_WAND_OF_LIGHTNING_BOLT \
	, const_proto_wands.PROTO_WAND_OF_LIGHTNING_BOLT_7TH \
	, const_proto_wands.PROTO_WAND_OF_LIGHTNING_BOLT_9TH \
	, const_proto_wands.PROTO_WAND_OF_LIGHTNING_BOLT_10TH\
	, ]

PROTOS_WANDS_ARCANE_LEVEL_3_ILLUSION = [ \
	 const_proto_wands.PROTO_WAND_OF_DISPLACEMENT \
	, const_proto_wands.PROTO_WAND_OF_INVISIBILITY_SPHERE\
	, ]

PROTOS_WANDS_ARCANE_LEVEL_3_NECROMANCY = [ \
	 const_proto_wands.PROTO_WAND_OF_HALT_UNDEAD \
	, const_proto_wands.PROTO_WAND_OF_VAMPIRIC_TOUCH\
	, ]

PROTOS_WANDS_ARCANE_LEVEL_3_TRANSMUTATION = [ \
	 const_proto_wands.PROTO_WAND_OF_BLINK \
	, const_proto_wands.PROTO_WAND_OF_GASEOUS_FORM \
	, const_proto_wands.PROTO_WAND_OF_GLIBNESS \
	, const_proto_wands.PROTO_WAND_OF_MAGIC_WEAPON_GREATER \
	, const_proto_wands.PROTO_WAND_OF_HASTE \
	, const_proto_wands.PROTO_WAND_OF_HASTE_USED \
	, const_proto_wands.PROTO_WAND_OF_KEEN_EDGE \
	, const_proto_wands.PROTO_WAND_OF_SLOW\
	, ]

PROTOS_WANDS_ARCANE_LEVEL_3 =  \
	 PROTOS_WANDS_ARCANE_LEVEL_3_ABJURATION \
	+ PROTOS_WANDS_ARCANE_LEVEL_3_CONJURATION \
	+ PROTOS_WANDS_ARCANE_LEVEL_3_DIVINATION \
	+ PROTOS_WANDS_ARCANE_LEVEL_3_ENCHANTMENT \
	+ PROTOS_WANDS_ARCANE_LEVEL_3_EVOCATION \
	+ PROTOS_WANDS_ARCANE_LEVEL_3_ILLUSION \
	+ PROTOS_WANDS_ARCANE_LEVEL_3_NECROMANCY \
	+ PROTOS_WANDS_ARCANE_LEVEL_3_TRANSMUTATION

PROTOS_WANDS_DIVINE_LEVEL_3_ABJURATION = [ \
	 const_proto_wands.PROTO_WAND_OF_NEGATIVE_ENERGY_PROTECTION \
	, const_proto_wands.PROTO_WAND_OF_PROTECTION_FROM_ENERGY\
	, ]

PROTOS_WANDS_DIVINE_LEVEL_3_CONJURATION = [ \
	 const_proto_wands.PROTO_WAND_OF_CURE_SERIOUS_WOUNDS \
	, const_proto_wands.PROTO_WAND_OF_REMOVE_BLINDNESS_DEAFNESS \
	, const_proto_wands.PROTO_WAND_OF_REMOVE_DISEASE \
	, const_proto_wands.PROTO_WAND_OF_SUMMON_NATURES_ALLY_III\
	, ]

PROTOS_WANDS_DIVINE_LEVEL_3_DIVINATION = []

PROTOS_WANDS_DIVINE_LEVEL_3_ENCHANTMENT = [ \
	 const_proto_wands.PROTO_WAND_OF_DOMINATE_ANIMAL \
	, const_proto_wands.PROTO_WAND_OF_PRAYER\
	, ]

PROTOS_WANDS_DIVINE_LEVEL_3_EVOCATION = [ \
	 const_proto_wands.PROTO_WAND_OF_CALL_LIGHTNING \
	, const_proto_wands.PROTO_WAND_OF_INVISIBILITY_PURGE \
	, const_proto_wands.PROTO_WAND_OF_SEARING_LIGHT \
	, const_proto_wands.PROTO_WAND_OF_WIND_WALL\
	, ]

PROTOS_WANDS_DIVINE_LEVEL_3_ILLUSION = []

PROTOS_WANDS_DIVINE_LEVEL_3_NECROMANCY = [ \
	 const_proto_wands.PROTO_WAND_OF_ANIMATE_DEAD \
	, const_proto_wands.PROTO_WAND_OF_BESTOW_CURSE \
	, const_proto_wands.PROTO_WAND_OF_CONTAGION \
	, const_proto_wands.PROTO_WAND_OF_INFLICT_SERIOUS_WOUNDS\
	, ]

PROTOS_WANDS_DIVINE_LEVEL_3_TRANSMUTATION = [ \
	 const_proto_wands.PROTO_WAND_OF_MAGIC_FANG_GREATER \
	, const_proto_wands.PROTO_WAND_OF_MAGIC_VESTMENT \
	, const_proto_wands.PROTO_WAND_OF_MELD_INTO_STONE \
	, const_proto_wands.PROTO_WAND_OF_QUENCH\
	, ]

PROTOS_WANDS_DIVINE_LEVEL_3 =  \
	 PROTOS_WANDS_DIVINE_LEVEL_3_ABJURATION \
	+ PROTOS_WANDS_DIVINE_LEVEL_3_CONJURATION \
	+ PROTOS_WANDS_DIVINE_LEVEL_3_DIVINATION \
	+ PROTOS_WANDS_DIVINE_LEVEL_3_ENCHANTMENT \
	+ PROTOS_WANDS_DIVINE_LEVEL_3_EVOCATION \
	+ PROTOS_WANDS_DIVINE_LEVEL_3_ILLUSION \
	+ PROTOS_WANDS_DIVINE_LEVEL_3_NECROMANCY \
	+ PROTOS_WANDS_DIVINE_LEVEL_3_TRANSMUTATION

PROTOS_WANDS_ARCANE_LEVEL_4_ABJURATION = [ \
	 const_proto_wands.PROTO_WAND_OF_DIMENSIONAL_ANCHOR \
	, const_proto_wands.PROTO_WAND_OF_FREEDOM_OF_MOVEMENT \
	, const_proto_wands.PROTO_WAND_OF_REMOVE_CURSE \
	, const_proto_wands.PROTO_WAND_OF_STONESKIN\
	, ]

PROTOS_WANDS_ARCANE_LEVEL_4_CONJURATION = [ \
	 const_proto_wands.PROTO_WAND_OF_DIMENSION_DOOR \
	, const_proto_wands.PROTO_WAND_OF_SOLID_FOG \
	, const_proto_wands.PROTO_WAND_OF_SUMMON_MONSTER_IV\
	, ]

PROTOS_WANDS_ARCANE_LEVEL_4_DIVINATION = []

PROTOS_WANDS_ARCANE_LEVEL_4_ENCHANTMENT = [ \
	 const_proto_wands.PROTO_WAND_OF_CHARM_MONSTER \
	, const_proto_wands.PROTO_WAND_OF_CONFUSION \
	, const_proto_wands.PROTO_WAND_OF_CRUSHING_DESPAIR\
	, ]

PROTOS_WANDS_ARCANE_LEVEL_4_EVOCATION = [ \
	 const_proto_wands.PROTO_WAND_OF_FIRE_SHIELD \
	, const_proto_wands.PROTO_WAND_OF_ICE_STORM \
	, const_proto_wands.PROTO_WAND_OF_OTILUKES_RESILIENT_SPHERE \
	, const_proto_wands.PROTO_WAND_OF_SHOUT\
	, ]

PROTOS_WANDS_ARCANE_LEVEL_4_ILLUSION = [ \
	 const_proto_wands.PROTO_WAND_OF_INVISIBILITY_GREATER \
	, const_proto_wands.PROTO_WAND_OF_PHANTASMAL_KILLER\
	, ]

PROTOS_WANDS_ARCANE_LEVEL_4_NECROMANCY = [ \
	 const_proto_wands.PROTO_WAND_OF_FEAR\
	, ]

PROTOS_WANDS_ARCANE_LEVEL_4_TRANSMUTATION = []

PROTOS_WANDS_ARCANE_LEVEL_4 =  \
	 PROTOS_WANDS_ARCANE_LEVEL_4_ABJURATION \
	+ PROTOS_WANDS_ARCANE_LEVEL_4_CONJURATION \
	+ PROTOS_WANDS_ARCANE_LEVEL_4_DIVINATION \
	+ PROTOS_WANDS_ARCANE_LEVEL_4_ENCHANTMENT \
	+ PROTOS_WANDS_ARCANE_LEVEL_4_EVOCATION \
	+ PROTOS_WANDS_ARCANE_LEVEL_4_ILLUSION \
	+ PROTOS_WANDS_ARCANE_LEVEL_4_NECROMANCY \
	+ PROTOS_WANDS_ARCANE_LEVEL_4_TRANSMUTATION

PROTOS_WANDS_DIVINE_LEVEL_4_ABJURATION = [ \
	 const_proto_wands.PROTO_WAND_OF_DISMISSAL \
	, const_proto_wands.PROTO_WAND_OF_REPEL_VERMIN\
	, ]

PROTOS_WANDS_DIVINE_LEVEL_4_CONJURATION = [ \
	 const_proto_wands.PROTO_WAND_OF_CURE_CRITICAL_WOUNDS \
	, const_proto_wands.PROTO_WAND_OF_NEUTRALIZE_POISON \
	, const_proto_wands.PROTO_WAND_OF_RESTORATION \
	, const_proto_wands.PROTO_WAND_OF_SUMMON_NATURES_ALLY_IV\
	, ]

PROTOS_WANDS_DIVINE_LEVEL_4_DIVINATION = [ \
	 const_proto_wands.PROTO_WAND_OF_DISCERN_LIES\
	, ]

PROTOS_WANDS_DIVINE_LEVEL_4_ENCHANTMENT = []

PROTOS_WANDS_DIVINE_LEVEL_4_EVOCATION = [ \
	 const_proto_wands.PROTO_WAND_OF_DIVINE_POWER \
	, const_proto_wands.PROTO_WAND_OF_HOLY_SWORD\
	, ]

PROTOS_WANDS_DIVINE_LEVEL_4_ILLUSION = []

PROTOS_WANDS_DIVINE_LEVEL_4_NECROMANCY = [ \
	 const_proto_wands.PROTO_WAND_OF_BLIGHT \
	, const_proto_wands.PROTO_WAND_OF_DEATH_WARD \
	, const_proto_wands.PROTO_WAND_OF_INFLICT_CRITICAL_WOUNDS \
	, const_proto_wands.PROTO_WAND_OF_POISON\
	, ]

PROTOS_WANDS_DIVINE_LEVEL_4_TRANSMUTATION = [ \
	 const_proto_wands.PROTO_WAND_OF_CONTROL_PLANTS \
	, const_proto_wands.PROTO_WAND_OF_GIANT_VERMIN \
	, const_proto_wands.PROTO_WAND_OF_REINCARNATION \
	, const_proto_wands.PROTO_WAND_OF_SPIKE_STONES\
	, ]

PROTOS_WANDS_DIVINE_LEVEL_4 =  \
	 PROTOS_WANDS_DIVINE_LEVEL_4_ABJURATION \
	+ PROTOS_WANDS_DIVINE_LEVEL_4_CONJURATION \
	+ PROTOS_WANDS_DIVINE_LEVEL_4_DIVINATION \
	+ PROTOS_WANDS_DIVINE_LEVEL_4_ENCHANTMENT \
	+ PROTOS_WANDS_DIVINE_LEVEL_4_EVOCATION \
	+ PROTOS_WANDS_DIVINE_LEVEL_4_ILLUSION \
	+ PROTOS_WANDS_DIVINE_LEVEL_4_NECROMANCY \
	+ PROTOS_WANDS_DIVINE_LEVEL_4_TRANSMUTATION

PROTOS_WANDS_ARCANE_LEVEL_5_ABJURATION = [ \
	 const_proto_wands.PROTO_WAND_OF_BREAK_ENCHANTMENT\
	, ]

PROTOS_WANDS_ARCANE_LEVEL_5_CONJURATION = [ \
	 const_proto_wands.PROTO_WAND_OF_CLOUDKILL \
	, const_proto_wands.PROTO_WAND_OF_SUMMON_MONSTER_V \
	, const_proto_wands.PROTO_WAND_OF_TELEPORT\
	, ]

PROTOS_WANDS_ARCANE_LEVEL_5_DIVINATION = []

PROTOS_WANDS_ARCANE_LEVEL_5_ENCHANTMENT = [ \
	 const_proto_wands.PROTO_WAND_OF_DOMINATE_PERSON \
	, const_proto_wands.PROTO_WAND_OF_FEEBLEMIND \
	, const_proto_wands.PROTO_WAND_OF_HOLD_MONSTER \
	, const_proto_wands.PROTO_WAND_OF_MIND_FOG\
	, ]

PROTOS_WANDS_ARCANE_LEVEL_5_EVOCATION = [ \
	 const_proto_wands.PROTO_WAND_OF_CONE_OF_COLD\
	, ]

PROTOS_WANDS_ARCANE_LEVEL_5_ILLUSION = []

PROTOS_WANDS_ARCANE_LEVEL_5_NECROMANCY = []

PROTOS_WANDS_ARCANE_LEVEL_5_TRANSMUTATION = []

PROTOS_WANDS_ARCANE_LEVEL_5 =  \
	 PROTOS_WANDS_ARCANE_LEVEL_5_ABJURATION \
	+ PROTOS_WANDS_ARCANE_LEVEL_5_CONJURATION \
	+ PROTOS_WANDS_ARCANE_LEVEL_5_DIVINATION \
	+ PROTOS_WANDS_ARCANE_LEVEL_5_ENCHANTMENT \
	+ PROTOS_WANDS_ARCANE_LEVEL_5_EVOCATION \
	+ PROTOS_WANDS_ARCANE_LEVEL_5_ILLUSION \
	+ PROTOS_WANDS_ARCANE_LEVEL_5_NECROMANCY \
	+ PROTOS_WANDS_ARCANE_LEVEL_5_TRANSMUTATION

PROTOS_WANDS_DIVINE_LEVEL_5_ABJURATION = [ \
	 const_proto_wands.PROTO_WAND_OF_DISPEL_AIR \
	, const_proto_wands.PROTO_WAND_OF_DISPEL_CHAOS \
	, const_proto_wands.PROTO_WAND_OF_DISPEL_EARTH \
	, const_proto_wands.PROTO_WAND_OF_DISPEL_EVIL \
	, const_proto_wands.PROTO_WAND_OF_DISPEL_FIRE \
	, const_proto_wands.PROTO_WAND_OF_DISPEL_GOOD \
	, const_proto_wands.PROTO_WAND_OF_DISPEL_LAW \
	, const_proto_wands.PROTO_WAND_OF_DISPEL_WATER \
	, const_proto_wands.PROTO_WAND_OF_SPELL_RESISTANCE\
	, ]

PROTOS_WANDS_DIVINE_LEVEL_5_CONJURATION = [ \
	 const_proto_wands.PROTO_WAND_OF_RAISE_DEAD \
	, const_proto_wands.PROTO_WAND_OF_SUMMON_NATURES_ALLY_V\
	, ]

PROTOS_WANDS_DIVINE_LEVEL_5_DIVINATION = [ \
	 const_proto_wands.PROTO_WAND_OF_TRUE_SEEING\
	, ]

PROTOS_WANDS_DIVINE_LEVEL_5_ENCHANTMENT = [ \
	 const_proto_wands.PROTO_WAND_OF_GREATER_COMMAND\
	, ]

PROTOS_WANDS_DIVINE_LEVEL_5_EVOCATION = [ \
	 const_proto_wands.PROTO_WAND_OF_CALL_LIGHTNING_STORM \
	, const_proto_wands.PROTO_WAND_OF_FLAME_STRIKE\
	, ]

PROTOS_WANDS_DIVINE_LEVEL_5_ILLUSION = []

PROTOS_WANDS_DIVINE_LEVEL_5_NECROMANCY = [ \
	 const_proto_wands.PROTO_WAND_OF_SLAY_LIVING\
	, ]

PROTOS_WANDS_DIVINE_LEVEL_5_TRANSMUTATION = [ \
	 const_proto_wands.PROTO_WAND_OF_ANIMAL_GROWTH \
	, const_proto_wands.PROTO_WAND_OF_RIGHTEOUS_MIGHT\
	, ]

PROTOS_WANDS_DIVINE_LEVEL_5 =  \
	 PROTOS_WANDS_DIVINE_LEVEL_5_ABJURATION \
	+ PROTOS_WANDS_DIVINE_LEVEL_5_CONJURATION \
	+ PROTOS_WANDS_DIVINE_LEVEL_5_DIVINATION \
	+ PROTOS_WANDS_DIVINE_LEVEL_5_ENCHANTMENT \
	+ PROTOS_WANDS_DIVINE_LEVEL_5_EVOCATION \
	+ PROTOS_WANDS_DIVINE_LEVEL_5_ILLUSION \
	+ PROTOS_WANDS_DIVINE_LEVEL_5_NECROMANCY \
	+ PROTOS_WANDS_DIVINE_LEVEL_5_TRANSMUTATION

