import const_proto_weapon

PROTOS_WEAPON_SIMPLE_MELEE_LIGHT_MASTERWORK = [\
	const_proto_weapon.PROTO_WEAPON_DAGGER_MASTERWORK \
	, const_proto_weapon.PROTO_WEAPON_DAGGER_THROWING_MASTERWORK \
	, const_proto_weapon.PROTO_WEAPON_MACE_LIGHT_MASTERWORK \
	, const_proto_weapon.PROTO_WEAPON_SICKLE_MASTERWORK \
	]

PROTOS_WEAPON_SIMPLE_MELEE_ONE_HANDED_MASTERWORK = [\
	const_proto_weapon.PROTO_WEAPON_CLUB_MASTERWORK \
	, const_proto_weapon.PROTO_WEAPON_MACE_HEAVY_MASTERWORK \
	, const_proto_weapon.PROTO_WEAPON_MORNINGSTAR_MASTERWORK \
	, const_proto_weapon.PROTO_WEAPON_SHORTSPEAR_MASTERWORK \
	]

PROTOS_WEAPON_SIMPLE_MELEE_TWO_HANDED_MASTERWORK = [\
	const_proto_weapon.PROTO_WEAPON_LONGSPEAR_MASTERWORK \
	, const_proto_weapon.PROTO_WEAPON_QUARTERSTAFF_MASTERWORK \
	, const_proto_weapon.PROTO_WEAPON_SPEAR_MASTERWORK \
	]

PROTOS_WEAPON_SIMPLE_MELEE_MASTERWORK = PROTOS_WEAPON_SIMPLE_MELEE_LIGHT_MASTERWORK + PROTOS_WEAPON_SIMPLE_MELEE_ONE_HANDED_MASTERWORK + PROTOS_WEAPON_SIMPLE_MELEE_TWO_HANDED_MASTERWORK

PROTOS_WEAPON_SIMPLE_RANGED_MASTERWORK = [\
	const_proto_weapon.PROTO_WEAPON_CROSSBOW_HEAVY_MASTERWORK \
	, const_proto_weapon.PROTO_WEAPON_CROSSBOW_LIGHT_MASTERWORK \
	, const_proto_weapon.PROTO_AMMO_BOLT_QUIVER \
	, const_proto_weapon.PROTO_WEAPON_JAVELIN_MASTERWORK \
	, const_proto_weapon.PROTO_WEAPON_DART_MASTERWORK \
	, const_proto_weapon.PROTO_WEAPON_SLING_MASTERWORK \
	, const_proto_weapon.PROTO_AMMO_BULLET_POUCH \
	]

PROTOS_WEAPON_SIMPLE_MASTERWORK = PROTOS_WEAPON_SIMPLE_MELEE_MASTERWORK + PROTOS_WEAPON_SIMPLE_RANGED_MASTERWORK

PROTOS_WEAPON_MARTIAL_MELEE_LIGHT_MASTERWORK = [\
	const_proto_weapon.PROTO_WEAPON_HAMMER_LIGHT_MASTERWORK \
	, const_proto_weapon.PROTO_WEAPON_HANDAXE_MASTERWORK \
	, const_proto_weapon.PROTO_WEAPON_KUKRI_MASTERWORK \
	, const_proto_weapon.PROTO_WEAPON_SICKLE_MASTERWORK \
	, const_proto_weapon.PROTO_WEAPON_SHORTSWORD_MASTERWORK \
	] # missing: Throwing Axe, Light Pick, Sap

PROTOS_WEAPON_MARTIAL_MELEE_ONE_HANDED_MASTERWORK = [\
	const_proto_weapon.PROTO_BATTLEAXE_MASTERWORK \
	, const_proto_weapon.PROTO_FLAIL_MASTERWORK \
	, const_proto_weapon.PROTO_LONGSWORD_MASTERWORK \
	, const_proto_weapon.PROTO_WEAPON_PICK_HEAVY_MASTERWORK \
	, const_proto_weapon.PROTO_RAPIER_MASTERWORK \
	, const_proto_weapon.PROTO_SCIMITAR_MASTERWORK \
	, const_proto_weapon.PROTO_WEAPON_TRIDENT_MASTERWORK \
	, const_proto_weapon.PROTO_WEAPON_WARHAMMER_MASTERWORK \
	]

PROTOS_WEAPON_MARTIAL_MELEE_TWO_HANDED_MASTERWORK = [\
	const_proto_weapon.PROTO_WEAPON_FALCHION_MASTERWORK \
	, const_proto_weapon.PROTO_WEAPON_GLAIVE_MASTERWORK \
	, const_proto_weapon.PROTO_WEAPON_GREATAXE_MASTERWORK \
	, const_proto_weapon.PROTO_WEAPON_GREATCLUB_MASTERWORK \
	, const_proto_weapon.PROTO_WEAPON_FLAIL_HEAVY_MASTERWORK \
	, const_proto_weapon.PROTO_WEAPON_GREATSWORD_MASTERWORK \
	, const_proto_weapon.PROTO_WEAPON_GUISARME_MASTERWORK \
	, const_proto_weapon.PROTO_WEAPON_HALBERD_MASTERWORK \
	, const_proto_weapon.PROTO_WEAPON_RANSEUR_MASTERWORK \
	, const_proto_weapon.PROTO_WEAPON_SCYTHE_MASTERWORK \
	] # missing: Lance

PROTOS_WEAPON_MARTIAL_MELEE_MASTERWORK = PROTOS_WEAPON_MARTIAL_MELEE_LIGHT_MASTERWORK + PROTOS_WEAPON_MARTIAL_MELEE_ONE_HANDED_MASTERWORK + PROTOS_WEAPON_MARTIAL_MELEE_TWO_HANDED_MASTERWORK

PROTOS_WEAPON_MARTIAL_RANGED_MASTERWORK = [\
	const_proto_weapon.PROTO_WEAPON_LONGBOW_MASTERWORK \
	, const_proto_weapon.PROTO_WEAPON_LONGBOW_COMPOSITE_12_MASTERWORK \
	, const_proto_weapon.PROTO_WEAPON_LONGBOW_COMPOSITE_14_MASTERWORK \
	, const_proto_weapon.PROTO_WEAPON_LONGBOW_COMPOSITE_16_MASTERWORK \
	, const_proto_weapon.PROTO_WEAPON_SHORTBOW_MASTERWORK \
	, const_proto_weapon.PROTO_AMMO_ARROW_QUIVER \
	] # missing: Shortbow Composite

PROTOS_WEAPON_MARTIAL_MASTERWORK = PROTOS_WEAPON_MARTIAL_MELEE_MASTERWORK + PROTOS_WEAPON_MARTIAL_RANGED_MASTERWORK

PROTOS_WEAPON_EXOTIC_MELEE_LIGHT_MASTERWORK = [\
	const_proto_weapon.PROTO_WEAPON_SPIKED_KAMA_MASTERWORK \
	, const_proto_weapon.PROTO_WEAPON_SPIKED_SIANGHAM_MASTERWORK \
	] # missing: Nunchaku, Sai

PROTOS_WEAPON_EXOTIC_MELEE_ONE_HANDED_MASTERWORK = [\
	const_proto_weapon.PROTO_WEAPON_SWORD_BASTARD_MASTERWORK \
	, const_proto_weapon.PROTO_WEAPON_WARAXE_DWARVEN_MASTERWORK \
	] # missing: Whip

PROTOS_WEAPON_EXOTIC_MELEE_TWO_HANDED_MASTERWORK = [\
	const_proto_weapon.PROTO_WEAPON_DOUBLEAXE_ORC_MASTERWORK \
	, const_proto_weapon.PROTO_WEAPON_SPIKED_CHAIN_MASTERWORK \
	, const_proto_weapon.PROTO_WEAPON_HAMMER_GNOME_HOOKED_MASTERWORK \
	] # missing: Dire Flail, Two-bladed Sword, Urgrosh

PROTOS_WEAPON_EXOTIC_MELEE_MASTERWORK = PROTOS_WEAPON_EXOTIC_MELEE_LIGHT_MASTERWORK + PROTOS_WEAPON_EXOTIC_MELEE_ONE_HANDED_MASTERWORK + PROTOS_WEAPON_EXOTIC_MELEE_TWO_HANDED_MASTERWORK

PROTOS_WEAPON_EXOTIC_RANGED_MASTERWORK = [\
	const_proto_weapon.PROTO_WEAPON_CROSSBOW_REPEATING_LIGHT_MASTERWORK \
	, const_proto_weapon.PROTO_WEAPON_SHURIKEN_MASTERWORK \
	] # missing: Bolas, Hand Crossbow, Repeating Heavy Crossbow, Net

PROTOS_WEAPON_EXOTIC_MASTERWORK = PROTOS_WEAPON_EXOTIC_MELEE_MASTERWORK + PROTOS_WEAPON_EXOTIC_RANGED_MASTERWORK
################## Upgrade 2 masterwork
def dmerge(d1, d2, d3 = None, d4 = None, d5 = None):
	result = d1.copy()
	result.update(d2)
	if (d3): result.update(d3)
	if (d4): result.update(d4)
	if (d5): result.update(d5)
	return result

PROTOS_WEAPON_SIMPLE_MELEE_LIGHT_2MASTERWORK = {\
	const_proto_weapon.PROTO_WEAPON_DAGGER : const_proto_weapon.PROTO_WEAPON_DAGGER_MASTERWORK\
	, const_proto_weapon.PROTO_WEAPON_DAGGER_THROWING : const_proto_weapon.PROTO_WEAPON_DAGGER_THROWING_MASTERWORK \
	, const_proto_weapon.PROTO_WEAPON_MACE_LIGHT : const_proto_weapon.PROTO_WEAPON_MACE_LIGHT_MASTERWORK \
	, const_proto_weapon.PROTO_WEAPON_SICKLE : const_proto_weapon.PROTO_WEAPON_SICKLE_MASTERWORK\
	}

PROTOS_WEAPON_SIMPLE_MELEE_ONE_HANDED_2MASTERWORK = {\
	const_proto_weapon.PROTO_WEAPON_CLUB : const_proto_weapon.PROTO_WEAPON_CLUB_MASTERWORK \
	, const_proto_weapon.PROTO_WEAPON_MACE_HEAVY : const_proto_weapon.PROTO_WEAPON_MACE_HEAVY_MASTERWORK \
	, const_proto_weapon.PROTO_WEAPON_MORNINGSTAR : const_proto_weapon.PROTO_WEAPON_MORNINGSTAR_MASTERWORK \
	, const_proto_weapon.PROTO_WEAPON_SHORTSPEAR : const_proto_weapon.PROTO_WEAPON_SHORTSPEAR_MASTERWORK \
	}

PROTOS_WEAPON_SIMPLE_MELEE_TWO_HANDED_2MASTERWORK = {\
	const_proto_weapon.PROTO_WEAPON_LONGSPEAR : const_proto_weapon.PROTO_WEAPON_LONGSPEAR_MASTERWORK \
	, const_proto_weapon.PROTO_WEAPON_QUARTERSTAFF : const_proto_weapon.PROTO_WEAPON_QUARTERSTAFF_MASTERWORK \
	, const_proto_weapon.PROTO_WEAPON_SPEAR : const_proto_weapon.PROTO_WEAPON_SPEAR_MASTERWORK \
	}

PROTOS_WEAPON_SIMPLE_MELEE_2MASTERWORK = dmerge(PROTOS_WEAPON_SIMPLE_MELEE_LIGHT_2MASTERWORK, PROTOS_WEAPON_SIMPLE_MELEE_ONE_HANDED_2MASTERWORK, PROTOS_WEAPON_SIMPLE_MELEE_TWO_HANDED_2MASTERWORK)

PROTOS_WEAPON_SIMPLE_RANGED_2MASTERWORK = {\
	const_proto_weapon.PROTO_WEAPON_CROSSBOW_HEAVY : const_proto_weapon.PROTO_WEAPON_CROSSBOW_HEAVY_MASTERWORK \
	, const_proto_weapon.PROTO_WEAPON_CROSSBOW_LIGHT : const_proto_weapon.PROTO_WEAPON_CROSSBOW_LIGHT_MASTERWORK \
	, const_proto_weapon.PROTO_WEAPON_JAVELIN : const_proto_weapon.PROTO_WEAPON_JAVELIN_MASTERWORK \
	, const_proto_weapon.PROTO_WEAPON_DART : const_proto_weapon.PROTO_WEAPON_DART_MASTERWORK \
	, const_proto_weapon.PROTO_WEAPON_SLING : const_proto_weapon.PROTO_WEAPON_SLING_MASTERWORK \
	}

PROTOS_WEAPON_SIMPLE_2MASTERWORK = dmerge(PROTOS_WEAPON_SIMPLE_MELEE_2MASTERWORK, PROTOS_WEAPON_SIMPLE_RANGED_2MASTERWORK)

PROTOS_WEAPON_MARTIAL_MELEE_LIGHT_2MASTERWORK = {\
	const_proto_weapon.PROTO_WEAPON_HAMMER_LIGHT : const_proto_weapon.PROTO_WEAPON_HAMMER_LIGHT_MASTERWORK \
	, const_proto_weapon.PROTO_WEAPON_HANDAXE : const_proto_weapon.PROTO_WEAPON_HANDAXE_MASTERWORK \
	, const_proto_weapon.PROTO_WEAPON_KUKRI : const_proto_weapon.PROTO_WEAPON_KUKRI_MASTERWORK \
	, const_proto_weapon.PROTO_WEAPON_SICKLE : const_proto_weapon.PROTO_WEAPON_SICKLE_MASTERWORK \
	, const_proto_weapon.PROTO_WEAPON_SHORTSWORD : const_proto_weapon.PROTO_WEAPON_SHORTSWORD_MASTERWORK \
	} # missing: Throwing Axe, Light Pick, Sap

PROTOS_WEAPON_MARTIAL_MELEE_ONE_HANDED_2MASTERWORK = {\
	const_proto_weapon.PROTO_BATTLEAXE : const_proto_weapon.PROTO_BATTLEAXE_MASTERWORK \
	, const_proto_weapon.PROTO_FLAIL : const_proto_weapon.PROTO_FLAIL_MASTERWORK \
	, const_proto_weapon.PROTO_LONGSWORD : const_proto_weapon.PROTO_LONGSWORD_MASTERWORK \
	, const_proto_weapon.PROTO_WEAPON_PICK_HEAVY : const_proto_weapon.PROTO_WEAPON_PICK_HEAVY_MASTERWORK \
	, const_proto_weapon.PROTO_RAPIER : const_proto_weapon.PROTO_RAPIER_MASTERWORK \
	, const_proto_weapon.PROTO_SCIMITAR : const_proto_weapon.PROTO_SCIMITAR_MASTERWORK \
	, const_proto_weapon.PROTO_WEAPON_TRIDENT : const_proto_weapon.PROTO_WEAPON_TRIDENT_MASTERWORK \
	, const_proto_weapon.PROTO_WEAPON_WARHAMMER : const_proto_weapon.PROTO_WEAPON_WARHAMMER_MASTERWORK \
	}

PROTOS_WEAPON_MARTIAL_MELEE_TWO_HANDED_2MASTERWORK = {\
	const_proto_weapon.PROTO_WEAPON_FALCHION : const_proto_weapon.PROTO_WEAPON_FALCHION_MASTERWORK \
	, const_proto_weapon.PROTO_WEAPON_GLAIVE : const_proto_weapon.PROTO_WEAPON_GLAIVE_MASTERWORK \
	, const_proto_weapon.PROTO_WEAPON_GREATAXE : const_proto_weapon.PROTO_WEAPON_GREATAXE_MASTERWORK \
	, const_proto_weapon.PROTO_WEAPON_GREATCLUB : const_proto_weapon.PROTO_WEAPON_GREATCLUB_MASTERWORK \
	, const_proto_weapon.PROTO_WEAPON_FLAIL_HEAVY : const_proto_weapon.PROTO_WEAPON_FLAIL_HEAVY_MASTERWORK \
	, const_proto_weapon.PROTO_WEAPON_GREATSWORD : const_proto_weapon.PROTO_WEAPON_GREATSWORD_MASTERWORK \
	, const_proto_weapon.PROTO_WEAPON_GUISARME : const_proto_weapon.PROTO_WEAPON_GUISARME_MASTERWORK \
	, const_proto_weapon.PROTO_WEAPON_HALBERD : const_proto_weapon.PROTO_WEAPON_HALBERD_MASTERWORK \
	, const_proto_weapon.PROTO_WEAPON_RANSEUR : const_proto_weapon.PROTO_WEAPON_RANSEUR_MASTERWORK \
	, const_proto_weapon.PROTO_WEAPON_SCYTHE : const_proto_weapon.PROTO_WEAPON_SCYTHE_MASTERWORK \
	} # missing: Lance

PROTOS_WEAPON_MARTIAL_MELEE_2MASTERWORK = dmerge(PROTOS_WEAPON_MARTIAL_MELEE_LIGHT_2MASTERWORK, PROTOS_WEAPON_MARTIAL_MELEE_ONE_HANDED_2MASTERWORK, PROTOS_WEAPON_MARTIAL_MELEE_TWO_HANDED_2MASTERWORK)

PROTOS_WEAPON_MARTIAL_RANGED_2MASTERWORK = {\
	const_proto_weapon.PROTO_WEAPON_LONGBOW : const_proto_weapon.PROTO_WEAPON_LONGBOW_MASTERWORK \
	, const_proto_weapon.PROTO_WEAPON_LONGBOW_COMPOSITE_12 : const_proto_weapon.PROTO_WEAPON_LONGBOW_COMPOSITE_12_MASTERWORK \
	, const_proto_weapon.PROTO_WEAPON_LONGBOW_COMPOSITE_14 : const_proto_weapon.PROTO_WEAPON_LONGBOW_COMPOSITE_14_MASTERWORK \
	, const_proto_weapon.PROTO_WEAPON_LONGBOW_COMPOSITE_16 : const_proto_weapon.PROTO_WEAPON_LONGBOW_COMPOSITE_16_MASTERWORK \
	, const_proto_weapon.PROTO_WEAPON_SHORTBOW : const_proto_weapon.PROTO_WEAPON_SHORTBOW_MASTERWORK \
	} # missing: Shortbow Composite

PROTOS_WEAPON_MARTIAL_2MASTERWORK = dmerge(PROTOS_WEAPON_MARTIAL_MELEE_2MASTERWORK, PROTOS_WEAPON_MARTIAL_RANGED_2MASTERWORK)

PROTOS_WEAPON_EXOTIC_MELEE_LIGHT_2MASTERWORK = {\
	const_proto_weapon.PROTO_WEAPON_SPIKED_KAMA : const_proto_weapon.PROTO_WEAPON_SPIKED_KAMA_MASTERWORK \
	, const_proto_weapon.PROTO_WEAPON_SPIKED_SIANGHAM : const_proto_weapon.PROTO_WEAPON_SPIKED_SIANGHAM_MASTERWORK \
	} # missing: Nunchaku, Sai

PROTOS_WEAPON_EXOTIC_MELEE_ONE_HANDED_2MASTERWORK = {\
	const_proto_weapon.PROTO_WEAPON_SWORD_BASTARD : const_proto_weapon.PROTO_WEAPON_SWORD_BASTARD_MASTERWORK \
	, const_proto_weapon.PROTO_WEAPON_WARAXE_DWARVEN : const_proto_weapon.PROTO_WEAPON_WARAXE_DWARVEN_MASTERWORK \
	} # missing: Whip

PROTOS_WEAPON_EXOTIC_MELEE_TWO_HANDED_2MASTERWORK = {\
	const_proto_weapon.PROTO_WEAPON_DOUBLEAXE_ORC : const_proto_weapon.PROTO_WEAPON_DOUBLEAXE_ORC_MASTERWORK \
	, const_proto_weapon.PROTO_WEAPON_SPIKED_CHAIN : const_proto_weapon.PROTO_WEAPON_SPIKED_CHAIN_MASTERWORK \
	, const_proto_weapon.PROTO_WEAPON_HAMMER_GNOME_HOOKED : const_proto_weapon.PROTO_WEAPON_HAMMER_GNOME_HOOKED_MASTERWORK \
	} # missing: Dire Flail, Two-bladed Sword, Urgrosh

PROTOS_WEAPON_EXOTIC_MELEE_2MASTERWORK = dmerge(PROTOS_WEAPON_EXOTIC_MELEE_LIGHT_2MASTERWORK, PROTOS_WEAPON_EXOTIC_MELEE_ONE_HANDED_2MASTERWORK, PROTOS_WEAPON_EXOTIC_MELEE_TWO_HANDED_2MASTERWORK)

PROTOS_WEAPON_EXOTIC_RANGED_2MASTERWORK = {\
	const_proto_weapon.PROTO_WEAPON_CROSSBOW_REPEATING_LIGHT : const_proto_weapon.PROTO_WEAPON_CROSSBOW_REPEATING_LIGHT_MASTERWORK \
	, const_proto_weapon.PROTO_WEAPON_SHURIKEN : const_proto_weapon.PROTO_WEAPON_SHURIKEN_MASTERWORK \
	} # missing: Bolas, Hand Crossbow, Repeating Heavy Crossbow, Net

PROTOS_WEAPON_EXOTIC_2MASTERWORK = dmerge(PROTOS_WEAPON_EXOTIC_MELEE_2MASTERWORK, PROTOS_WEAPON_EXOTIC_RANGED_2MASTERWORK)

PROTOS_WEAPON_2MASTERWORK = dmerge(PROTOS_WEAPON_SIMPLE_2MASTERWORK, PROTOS_WEAPON_MARTIAL_2MASTERWORK, PROTOS_WEAPON_EXOTIC_2MASTERWORK)