import const_proto_wondrous

PROTOS_WONDROUS_MINOR = [ \
	const_proto_wondrous.PROTO_WONDROUS_AMULET_OF_HEALTH_PLUS_2 \
	, const_proto_wondrous.PROTO_WONDROUS_AMULET_OF_MIGHTY_FISTS_PLUS_1 \
	, const_proto_wondrous.PROTO_WONDROUS_AMULET_OF_NATURAL_ARMOR_PLUS_1 \
	, const_proto_wondrous.PROTO_WONDROUS_AMULET_OF_WISDOM_PLUS_2 \
	, const_proto_wondrous.PROTO_WONDROUS_BOOTS_OF_ELVENKIND \
	, const_proto_wondrous.PROTO_WONDROUS_BOOTS_OF_THE_WINTERLANDS \
	, const_proto_wondrous.PROTO_WONDROUS_BRACERS_OF_ARCHERY_LESSER \
	, const_proto_wondrous.PROTO_WONDROUS_BRACERS_OF_ARMOR_PLUS_1 \
	, const_proto_wondrous.PROTO_WONDROUS_BRACERS_OF_ARMOR_PLUS_2 \
	, const_proto_wondrous.PROTO_WONDROUS_CIRCLET_OF_BLASTING_MINOR \
	, const_proto_wondrous.PROTO_WONDROUS_CIRCLET_OF_PERSUASION \
	, const_proto_wondrous.PROTO_WONDROUS_CLOAK_OF_CHARISMA_PLUS_2 \
	, const_proto_wondrous.PROTO_WONDROUS_CLOAK_OF_CHARISMA_PLUS_2_BLACK \
	, const_proto_wondrous.PROTO_WONDROUS_CLOAK_OF_CHARISMA_PLUS_2_BLUE \
	, const_proto_wondrous.PROTO_WONDROUS_CLOAK_OF_CHARISMA_PLUS_2_STARS \
	, const_proto_wondrous.PROTO_WONDROUS_CLOAK_OF_CHARISMA_PLUS_2_WHITE \
	, const_proto_wondrous.PROTO_WONDROUS_CLOAK_OF_ELVENKIND \
	, const_proto_wondrous.PROTO_WONDROUS_CLOAK_OF_ELVENKIND_BLACK \
	, const_proto_wondrous.PROTO_WONDROUS_CLOAK_OF_ELVENKIND_FUR \
	, const_proto_wondrous.PROTO_WONDROUS_CLOAK_OF_ELVENKIND_GREEN \
	, const_proto_wondrous.PROTO_WONDROUS_CLOAK_OF_RESISTANCE_PLUS_1_BLACK \
	, const_proto_wondrous.PROTO_WONDROUS_CLOAK_OF_RESISTANCE_PLUS_1_BLUE \
	, const_proto_wondrous.PROTO_WONDROUS_CLOAK_OF_RESISTANCE_PLUS_1_FUR \
	, const_proto_wondrous.PROTO_WONDROUS_CLOAK_OF_RESISTANCE_PLUS_1_GREEN \
	, const_proto_wondrous.PROTO_WONDROUS_CLOAK_OF_RESISTANCE_PLUS_1_LIGHT_BLUE \
	, const_proto_wondrous.PROTO_WONDROUS_CLOAK_OF_RESISTANCE_PLUS_1_ORANGE \
	, const_proto_wondrous.PROTO_WONDROUS_CLOAK_OF_RESISTANCE_PLUS_1_RED \
	, const_proto_wondrous.PROTO_WONDROUS_CLOAK_OF_RESISTANCE_PLUS_1_VIOLET \
	, const_proto_wondrous.PROTO_WONDROUS_CLOAK_OF_RESISTANCE_PLUS_1_WHITE \
	, const_proto_wondrous.PROTO_WONDROUS_CLOAK_OF_RESISTANCE_PLUS_2_BLACK \
	, const_proto_wondrous.PROTO_WONDROUS_CLOAK_OF_RESISTANCE_PLUS_2_BLUE \
	, const_proto_wondrous.PROTO_WONDROUS_CLOAK_OF_RESISTANCE_PLUS_2_FUR \
	, const_proto_wondrous.PROTO_WONDROUS_CLOAK_OF_RESISTANCE_PLUS_2_GREEN \
	, const_proto_wondrous.PROTO_WONDROUS_CLOAK_OF_RESISTANCE_PLUS_2_LIGHT_BLUE \
	, const_proto_wondrous.PROTO_WONDROUS_CLOAK_OF_RESISTANCE_PLUS_2_ORANGE \
	, const_proto_wondrous.PROTO_WONDROUS_CLOAK_OF_RESISTANCE_PLUS_2_RED \
	, const_proto_wondrous.PROTO_WONDROUS_CLOAK_OF_RESISTANCE_PLUS_2_VIOLET \
	, const_proto_wondrous.PROTO_WONDROUS_CLOAK_OF_RESISTANCE_PLUS_2_WHITE \
	, const_proto_wondrous.PROTO_WONDROUS_DRUIDS_VESTMENTS \
	, const_proto_wondrous.PROTO_WONDROUS_EYES_OF_THE_EAGLE \
	, const_proto_wondrous.PROTO_WONDROUS_GAUNTLETS_OF_OGRE_POWER \
	, const_proto_wondrous.PROTO_WONDROUS_GLOVES_OF_DEXTERITY_PLUS_2 \
	, const_proto_wondrous.PROTO_WONDROUS_GOGGLES_OF_MINUTE_SEEING \
	, const_proto_wondrous.PROTO_WONDROUS_HEADBAND_OF_INTELLECT_PLUS_2 \
	, const_proto_wondrous.PROTO_WONDROUS_HELM_OF_READING_MAGIC \
	, const_proto_wondrous.PROTO_WONDROUS_VEST_OF_ESCAPE \
]
PROTOS_WONDROUS_MEDIUM = [ \
	const_proto_wondrous.PROTO_WONDROUS_AMULET_OF_HEALTH_PLUS_4 \
	, const_proto_wondrous.PROTO_WONDROUS_AMULET_OF_MIGHTY_FISTS_PLUS_2 \
	, const_proto_wondrous.PROTO_WONDROUS_AMULET_OF_NATURAL_ARMOR_PLUS_2 \
	, const_proto_wondrous.PROTO_WONDROUS_AMULET_OF_NATURAL_ARMOR_PLUS_3 \
	, const_proto_wondrous.PROTO_WONDROUS_AMULET_OF_WISDOM_PLUS_4 \
	, const_proto_wondrous.PROTO_WONDROUS_BELT_OF_GIANT_STRENGTH_PLUS_4 \
	, const_proto_wondrous.PROTO_WONDROUS_BOOTS_OF_SPEED \
	, const_proto_wondrous.PROTO_WONDROUS_BRACERS_OF_ARCHERY_GREATER \
	, const_proto_wondrous.PROTO_WONDROUS_BRACERS_OF_ARMOR_PLUS_3 \
	, const_proto_wondrous.PROTO_WONDROUS_BRACERS_OF_ARMOR_PLUS_4 \
	, const_proto_wondrous.PROTO_WONDROUS_BRACERS_OF_ARMOR_PLUS_5 \
	, const_proto_wondrous.PROTO_WONDROUS_CAPE_OF_THE_MOUNTEBANK \
	, const_proto_wondrous.PROTO_WONDROUS_CAPE_OF_THE_MOUNTEBANK_BLACK \
	, const_proto_wondrous.PROTO_WONDROUS_CAPE_OF_THE_MOUNTEBANK_BLUE \
	, const_proto_wondrous.PROTO_WONDROUS_CAPE_OF_THE_MOUNTEBANK_GREEN \
	, const_proto_wondrous.PROTO_WONDROUS_CLOAK_OF_ARACHNIDA \
	, const_proto_wondrous.PROTO_WONDROUS_CLOAK_OF_ARACHNIDA_BLACK \
	, const_proto_wondrous.PROTO_WONDROUS_CLOAK_OF_ARACHNIDA_RED \
	, const_proto_wondrous.PROTO_WONDROUS_CLOAK_OF_ARACHNIDA_SPIRAL \
	, const_proto_wondrous.PROTO_WONDROUS_CLOAK_OF_CHARISMA_PLUS_4 \
	, const_proto_wondrous.PROTO_WONDROUS_CLOAK_OF_CHARISMA_PLUS_4_BLACK \
	, const_proto_wondrous.PROTO_WONDROUS_CLOAK_OF_CHARISMA_PLUS_4_BLUE \
	, const_proto_wondrous.PROTO_WONDROUS_CLOAK_OF_CHARISMA_PLUS_4_STARS \
	, const_proto_wondrous.PROTO_WONDROUS_CLOAK_OF_CHARISMA_PLUS_4_WHITE \
	, const_proto_wondrous.PROTO_WONDROUS_CLOAK_OF_DISPLACEMENT_MINOR \
	, const_proto_wondrous.PROTO_WONDROUS_CLOAK_OF_RESISTANCE_PLUS_3_BLACK \
	, const_proto_wondrous.PROTO_WONDROUS_CLOAK_OF_RESISTANCE_PLUS_3_BLUE \
	, const_proto_wondrous.PROTO_WONDROUS_CLOAK_OF_RESISTANCE_PLUS_3_FUR \
	, const_proto_wondrous.PROTO_WONDROUS_CLOAK_OF_RESISTANCE_PLUS_3_GREEN \
	, const_proto_wondrous.PROTO_WONDROUS_CLOAK_OF_RESISTANCE_PLUS_3_LIGHT_BLUE \
	, const_proto_wondrous.PROTO_WONDROUS_CLOAK_OF_RESISTANCE_PLUS_3_ORANGE \
	, const_proto_wondrous.PROTO_WONDROUS_CLOAK_OF_RESISTANCE_PLUS_3_RED \
	, const_proto_wondrous.PROTO_WONDROUS_CLOAK_OF_RESISTANCE_PLUS_3_VIOLET \
	, const_proto_wondrous.PROTO_WONDROUS_CLOAK_OF_RESISTANCE_PLUS_3_WHITE \
	, const_proto_wondrous.PROTO_WONDROUS_CLOAK_OF_RESISTANCE_PLUS_4_BLACK \
	, const_proto_wondrous.PROTO_WONDROUS_CLOAK_OF_RESISTANCE_PLUS_4_BLUE \
	, const_proto_wondrous.PROTO_WONDROUS_CLOAK_OF_RESISTANCE_PLUS_4_FUR \
	, const_proto_wondrous.PROTO_WONDROUS_CLOAK_OF_RESISTANCE_PLUS_4_GREEN \
	, const_proto_wondrous.PROTO_WONDROUS_CLOAK_OF_RESISTANCE_PLUS_4_LIGHT_BLUE \
	, const_proto_wondrous.PROTO_WONDROUS_CLOAK_OF_RESISTANCE_PLUS_4_ORANGE \
	, const_proto_wondrous.PROTO_WONDROUS_CLOAK_OF_RESISTANCE_PLUS_4_RED \
	, const_proto_wondrous.PROTO_WONDROUS_CLOAK_OF_RESISTANCE_PLUS_4_VIOLET \
	, const_proto_wondrous.PROTO_WONDROUS_CLOAK_OF_RESISTANCE_PLUS_4_WHITE \
	, const_proto_wondrous.PROTO_WONDROUS_CLOAK_OF_RESISTANCE_PLUS_5_BLACK \
	, const_proto_wondrous.PROTO_WONDROUS_CLOAK_OF_RESISTANCE_PLUS_5_BLUE \
	, const_proto_wondrous.PROTO_WONDROUS_CLOAK_OF_RESISTANCE_PLUS_5_FUR \
	, const_proto_wondrous.PROTO_WONDROUS_CLOAK_OF_RESISTANCE_PLUS_5_GREEN \
	, const_proto_wondrous.PROTO_WONDROUS_CLOAK_OF_RESISTANCE_PLUS_5_LIGHT_BLUE \
	, const_proto_wondrous.PROTO_WONDROUS_CLOAK_OF_RESISTANCE_PLUS_5_ORANGE \
	, const_proto_wondrous.PROTO_WONDROUS_CLOAK_OF_RESISTANCE_PLUS_5_RED \
	, const_proto_wondrous.PROTO_WONDROUS_CLOAK_OF_RESISTANCE_PLUS_5_VIOLET \
	, const_proto_wondrous.PROTO_WONDROUS_CLOAK_OF_RESISTANCE_PLUS_5_WHITE \
	, const_proto_wondrous.PROTO_WONDROUS_GLOVES_OF_DEXTERITY_PLUS_4 \
	, const_proto_wondrous.PROTO_WONDROUS_HEADBAND_OF_INTELLECT_PLUS_4 \
	, const_proto_wondrous.PROTO_WONDROUS_HELM_OF_TELEPATHY \
	, const_proto_wondrous.PROTO_WONDROUS_NECKLACE_OF_ADAPTATION \
	, const_proto_wondrous.PROTO_WONDROUS_PERIAPT_OF_WOUND_CLOSURE \
]

PROTOS_WONDROUS_MAJOR = [ \
	const_proto_wondrous.PROTO_WONDROUS_AMULET_OF_HEALTH_PLUS_6 \
	, const_proto_wondrous.PROTO_WONDROUS_AMULET_OF_MIGHTY_FISTS_PLUS_3 \
	, const_proto_wondrous.PROTO_WONDROUS_AMULET_OF_MIGHTY_FISTS_PLUS_4 \
	, const_proto_wondrous.PROTO_WONDROUS_AMULET_OF_MIGHTY_FISTS_PLUS_5 \
	, const_proto_wondrous.PROTO_WONDROUS_AMULET_OF_NATURAL_ARMOR_PLUS_4 \
	, const_proto_wondrous.PROTO_WONDROUS_AMULET_OF_NATURAL_ARMOR_PLUS_5 \
	, const_proto_wondrous.PROTO_WONDROUS_AMULET_OF_WISDOM_PLUS_6 \
	, const_proto_wondrous.PROTO_WONDROUS_BELT_OF_GIANT_STRENGTH_PLUS_6 \
	, const_proto_wondrous.PROTO_WONDROUS_CLOAK_OF_CHARISMA_PLUS_6 \
	, const_proto_wondrous.PROTO_WONDROUS_CLOAK_OF_CHARISMA_PLUS_6_BLACK \
	, const_proto_wondrous.PROTO_WONDROUS_CLOAK_OF_CHARISMA_PLUS_6_BLUE \
	, const_proto_wondrous.PROTO_WONDROUS_CLOAK_OF_CHARISMA_PLUS_6_STARS \
	, const_proto_wondrous.PROTO_WONDROUS_CLOAK_OF_CHARISMA_PLUS_6_WHITE \
	, const_proto_wondrous.PROTO_WONDROUS_CLOAK_OF_DISPLACEMENT_MAJOR \
	, const_proto_wondrous.PROTO_WONDROUS_EYES_OF_CHARMING \
	, const_proto_wondrous.PROTO_WONDROUS_GLOVES_OF_DEXTERITY_PLUS_6 \
	, const_proto_wondrous.PROTO_WONDROUS_HEADBAND_OF_INTELLECT_PLUS_6 \
	, const_proto_wondrous.PROTO_WONDROUS_HELM_OF_BRILLIANCE \
	, const_proto_wondrous.PROTO_WONDROUS_HELM_OF_TELEPORTATION \
	, const_proto_wondrous.PROTO_WONDROUS_MANTLE_OF_SPELL_RESISTANCE \
	, const_proto_wondrous.PROTO_WONDROUS_MANTLE_OF_SPELL_RESISTANCE_BLACK \
	, const_proto_wondrous.PROTO_WONDROUS_MANTLE_OF_SPELL_RESISTANCE_BLUE \
	, const_proto_wondrous.PROTO_WONDROUS_MANTLE_OF_SPELL_RESISTANCE_STARS \
	, const_proto_wondrous.PROTO_WONDROUS_MANTLE_OF_SPELL_RESISTANCE_VIOLET \
	, const_proto_wondrous.PROTO_WONDROUS_ROBE_OF_BLENDING \
	, const_proto_wondrous.PROTO_WONDROUS_ROBE_OF_EYES \
	, const_proto_wondrous.PROTO_WONDROUS_ROBE_OF_THE_ARCHMAGI_BLACK \
	, const_proto_wondrous.PROTO_WONDROUS_ROBE_OF_THE_ARCHMAGI_GREY \
	, const_proto_wondrous.PROTO_WONDROUS_ROBE_OF_THE_ARCHMAGI_WHITE \
]

PROTOS_WONDROUS = PROTOS_WONDROUS_MINOR + PROTOS_WONDROUS_MEDIUM + PROTOS_WONDROUS_MAJOR