import const_proto_potions

PROTOS_POTIONS_ARCANE_LEVEL_1_TRANSMUTATION = [ \
	 const_proto_potions.PROTO_POTION_OF_ENLARGE_PERSON \
	, const_proto_potions.PROTO_POTION_OF_REDUCE_PERSON\
	, const_proto_potions.PROTO_POTION_OF_MAGE_ARMOR\
	, ]

PROTOS_POTIONS_ARCANE_LEVEL_1 =  \
	 PROTOS_POTIONS_ARCANE_LEVEL_1_TRANSMUTATION

PROTOS_POTIONS_DIVINE_LEVEL_1_CONJURATION = [ \
	 const_proto_potions.PROTO_POTION_OF_CURE_LIGHT_WOUNDS\
	, ]

PROTOS_POTIONS_DIVINE_LEVEL_1_TRANSMUTATION = [ \
	 const_proto_potions.PROTO_POTION_OF_GLIBNESS\
	, ]

PROTOS_POTIONS_DIVINE_LEVEL_1 =  \
	 PROTOS_POTIONS_DIVINE_LEVEL_1_CONJURATION \
	+ PROTOS_POTIONS_DIVINE_LEVEL_1_TRANSMUTATION

PROTOS_POTIONS_LEVEL_1 = PROTOS_POTIONS_ARCANE_LEVEL_1 + PROTOS_POTIONS_DIVINE_LEVEL_1

PROTOS_POTIONS_ARCANE_LEVEL_2_ABJURATION = [ \
	 const_proto_potions.PROTO_POTION_OF_PROTECTION_FROM_ARROWS\
	, ]

PROTOS_POTIONS_ARCANE_LEVEL_2_ILLUSION = [ \
	 const_proto_potions.PROTO_POTION_OF_BLUR \
	, const_proto_potions.PROTO_POTION_OF_INVISIBILITY\
	, ]

PROTOS_POTIONS_ARCANE_LEVEL_2_TRANSMUTATION = [ \
	 const_proto_potions.PROTO_POTION_OF_BULLS_STRENGTH \
	, const_proto_potions.PROTO_POTION_OF_CATS_GRACE \
	, const_proto_potions.PROTO_POTION_OF_EAGLES_SPLENDOR \
	, const_proto_potions.PROTO_POTION_OF_OWLS_WISDOM\
	, ]

PROTOS_POTIONS_ARCANE_LEVEL_2 =  \
	 PROTOS_POTIONS_ARCANE_LEVEL_2_ABJURATION \
	+ PROTOS_POTIONS_ARCANE_LEVEL_2_ILLUSION \
	+ PROTOS_POTIONS_ARCANE_LEVEL_2_TRANSMUTATION

PROTOS_POTIONS_DIVINE_LEVEL_2_CONJURATION = [ \
	 const_proto_potions.PROTO_POTION_OF_CURE_MODERATE_WOUNDS \
	, const_proto_potions.PROTO_POTION_OF_DELAY_POISON\
	, ]

PROTOS_POTIONS_DIVINE_LEVEL_2_ENCHANTMENT = [ \
	 const_proto_potions.PROTO_POTION_OF_AID\
	, ]

PROTOS_POTIONS_DIVINE_LEVEL_2_TRANSMUTATION = [ \
	 const_proto_potions.PROTO_POTION_OF_BARKSKIN\
	, ]

PROTOS_POTIONS_DIVINE_LEVEL_2 =  \
	 PROTOS_POTIONS_DIVINE_LEVEL_2_CONJURATION \
	+ PROTOS_POTIONS_DIVINE_LEVEL_2_ENCHANTMENT \
	+ PROTOS_POTIONS_DIVINE_LEVEL_2_TRANSMUTATION

PROTOS_POTIONS_LEVEL_2 = PROTOS_POTIONS_ARCANE_LEVEL_2 + PROTOS_POTIONS_DIVINE_LEVEL_2

PROTOS_POTIONS_ARCANE_LEVEL_3_ENCHANTMENT = [ \
	 const_proto_potions.PROTO_POTION_OF_HEROISM \
	, const_proto_potions.PROTO_POTION_OF_RAGE\
	, ]

PROTOS_POTIONS_ARCANE_LEVEL_3_ILLUSION = [ \
	 const_proto_potions.PROTO_POTION_OF_DISPLACEMENT\
	, ]

PROTOS_POTIONS_ARCANE_LEVEL_3_TRANSMUTATION = [ \
	 const_proto_potions.PROTO_POTION_OF_HASTE\
	, ]

PROTOS_POTIONS_ARCANE_LEVEL_3 =  \
	 PROTOS_POTIONS_ARCANE_LEVEL_3_ENCHANTMENT \
	+ PROTOS_POTIONS_ARCANE_LEVEL_3_ILLUSION \
	+ PROTOS_POTIONS_ARCANE_LEVEL_3_TRANSMUTATION

PROTOS_POTIONS_DIVINE_LEVEL_3_ABJURATION = [ \
	 const_proto_potions.PROTO_POTION_OF_REPEL_VERMIN\
	, ]

PROTOS_POTIONS_DIVINE_LEVEL_3_CONJURATION = [ \
	 const_proto_potions.PROTO_POTION_OF_CURE_SERIOUS_WOUNDS \
	, const_proto_potions.PROTO_POTION_OF_REMOVE_DISEASE\
	, ]

PROTOS_POTIONS_DIVINE_LEVEL_3_DIVINATION = [ \
	 const_proto_potions.PROTO_POTION_OF_DISCERN_LIES\
	, ]

PROTOS_POTIONS_DIVINE_LEVEL_3_TRANSMUTATION = [ \
	 const_proto_potions.PROTO_POTION_OF_GREATER_MAGIC_FANG\
	, ]

PROTOS_POTIONS_DIVINE_LEVEL_3 =  \
	 PROTOS_POTIONS_DIVINE_LEVEL_3_ABJURATION \
	+ PROTOS_POTIONS_DIVINE_LEVEL_3_CONJURATION \
	+ PROTOS_POTIONS_DIVINE_LEVEL_3_DIVINATION \
	+ PROTOS_POTIONS_DIVINE_LEVEL_3_TRANSMUTATION

PROTOS_POTIONS_LEVEL_3 = PROTOS_POTIONS_ARCANE_LEVEL_3 + PROTOS_POTIONS_DIVINE_LEVEL_3
