import const_proto_scrolls

PROTOS_SCROLLS_ARCANE_LEVEL_0_ABJURATION = [ \
	 const_proto_scrolls.PROTO_SCROLL_OF_RESISTANCE\
	, ]

PROTOS_SCROLLS_ARCANE_LEVEL_0_CONJURATION = [ \
	 const_proto_scrolls.PROTO_SCROLL_OF_ACID_SPLASH\
	, ]

PROTOS_SCROLLS_ARCANE_LEVEL_0_DIVINATION = [ \
	 const_proto_scrolls.PROTO_SCROLL_OF_DETECT_MAGIC \
	, const_proto_scrolls.PROTO_SCROLL_OF_READ_MAGIC\
	, ]

PROTOS_SCROLLS_ARCANE_LEVEL_0_ENCHANTMENT = [ \
	 const_proto_scrolls.PROTO_SCROLL_OF_DAZE\
	, ]

PROTOS_SCROLLS_ARCANE_LEVEL_0_EVOCATION = [ \
	 const_proto_scrolls.PROTO_SCROLL_OF_FLARE \
	, const_proto_scrolls.PROTO_SCROLL_OF_RAY_OF_FROST\
	, ]

PROTOS_SCROLLS_ARCANE_LEVEL_0_ILLUSION = []

PROTOS_SCROLLS_ARCANE_LEVEL_0_NECROMANCY = [ \
	 const_proto_scrolls.PROTO_SCROLL_OF_DISRUPT_UNDEAD\
	, ]

PROTOS_SCROLLS_ARCANE_LEVEL_0_TRANSMUTATION = [ \
	 const_proto_scrolls.PROTO_SCROLL_OF_OPEN_CLOSE\
	, ]

PROTOS_WANDS_ARCANE_LEVEL_0 =  \
	 PROTOS_SCROLLS_ARCANE_LEVEL_0_ABJURATION \
	+ PROTOS_SCROLLS_ARCANE_LEVEL_0_CONJURATION \
	+ PROTOS_SCROLLS_ARCANE_LEVEL_0_DIVINATION \
	+ PROTOS_SCROLLS_ARCANE_LEVEL_0_ENCHANTMENT \
	+ PROTOS_SCROLLS_ARCANE_LEVEL_0_EVOCATION \
	+ PROTOS_SCROLLS_ARCANE_LEVEL_0_ILLUSION \
	+ PROTOS_SCROLLS_ARCANE_LEVEL_0_NECROMANCY \
	+ PROTOS_SCROLLS_ARCANE_LEVEL_0_TRANSMUTATION

PROTOS_SCROLLS_DIVINE_LEVEL_0_ABJURATION = []

PROTOS_SCROLLS_DIVINE_LEVEL_0_CONJURATION = [ \
	 const_proto_scrolls.PROTO_SCROLL_OF_CURE_MINOR_WOUNDS\
	, ]

PROTOS_SCROLLS_DIVINE_LEVEL_0_DIVINATION = [ \
	 const_proto_scrolls.PROTO_SCROLL_OF_GUIDANCE\
	, ]

PROTOS_SCROLLS_DIVINE_LEVEL_0_ENCHANTMENT = []

PROTOS_SCROLLS_DIVINE_LEVEL_0_EVOCATION = []

PROTOS_SCROLLS_DIVINE_LEVEL_0_ILLUSION = []

PROTOS_SCROLLS_DIVINE_LEVEL_0_NECROMANCY = [ \
	 const_proto_scrolls.PROTO_SCROLL_OF_INFLICT_MINOR_WOUNDS\
	, ]

PROTOS_SCROLLS_DIVINE_LEVEL_0_TRANSMUTATION = [ \
	 const_proto_scrolls.PROTO_SCROLL_OF_VIRTUE\
	, ]

PROTOS_WANDS_DIVINE_LEVEL_0 =  \
	 PROTOS_SCROLLS_DIVINE_LEVEL_0_ABJURATION \
	+ PROTOS_SCROLLS_DIVINE_LEVEL_0_CONJURATION \
	+ PROTOS_SCROLLS_DIVINE_LEVEL_0_DIVINATION \
	+ PROTOS_SCROLLS_DIVINE_LEVEL_0_ENCHANTMENT \
	+ PROTOS_SCROLLS_DIVINE_LEVEL_0_EVOCATION \
	+ PROTOS_SCROLLS_DIVINE_LEVEL_0_ILLUSION \
	+ PROTOS_SCROLLS_DIVINE_LEVEL_0_NECROMANCY \
	+ PROTOS_SCROLLS_DIVINE_LEVEL_0_TRANSMUTATION

PROTOS_SCROLLS_ARCANE_LEVEL_1_ABJURATION = [ \
	 const_proto_scrolls.PROTO_SCROLL_OF_ENDURE_ELEMENTS \
	, const_proto_scrolls.PROTO_SCROLL_OF_PROTECTION_FROM_CHAOS \
	, const_proto_scrolls.PROTO_SCROLL_OF_PROTECTION_FROM_EVIL \
	, const_proto_scrolls.PROTO_SCROLL_OF_PROTECTION_FROM_GOOD \
	, const_proto_scrolls.PROTO_SCROLL_OF_PROTECTION_FROM_LAW \
	, const_proto_scrolls.PROTO_SCROLL_OF_REMOVE_FEAR \
	, const_proto_scrolls.PROTO_SCROLL_OF_SHIELD\
	, ]

PROTOS_SCROLLS_ARCANE_LEVEL_1_CONJURATION = [ \
	 const_proto_scrolls.PROTO_SCROLL_OF_GREASE \
	, const_proto_scrolls.PROTO_SCROLL_OF_MAGE_ARMOR \
	, const_proto_scrolls.PROTO_SCROLL_OF_OBSCURING_MIST \
	, const_proto_scrolls.PROTO_SCROLL_OF_SUMMON_MONSTER_I\
	, ]

PROTOS_SCROLLS_ARCANE_LEVEL_1_DIVINATION = [ \
	 const_proto_scrolls.PROTO_SCROLL_OF_DETECT_SECRET_DOORS \
	, const_proto_scrolls.PROTO_SCROLL_OF_DETECT_UNDEAD \
	, const_proto_scrolls.PROTO_SCROLL_OF_IDENTIFY \
	, const_proto_scrolls.PROTO_SCROLL_OF_TRUE_STRIKE\
	, ]

PROTOS_SCROLLS_ARCANE_LEVEL_1_ENCHANTMENT = [ \
	 const_proto_scrolls.PROTO_SCROLL_OF_CHARM_PERSON \
	, const_proto_scrolls.PROTO_SCROLL_OF_CONFUSION_LESSER \
	, const_proto_scrolls.PROTO_SCROLL_OF_SLEEP\
	, ]

PROTOS_SCROLLS_ARCANE_LEVEL_1_EVOCATION = [ \
	 const_proto_scrolls.PROTO_SCROLL_OF_BURNING_HANDS \
	, const_proto_scrolls.PROTO_SCROLL_OF_MAGIC_MISSILE \
	, const_proto_scrolls.PROTO_SCROLL_OF_SHOCKING_GRASP\
	, ]

PROTOS_SCROLLS_ARCANE_LEVEL_1_ILLUSION = [ \
	 const_proto_scrolls.PROTO_SCROLL_OF_COLOR_SPRAY\
	, ]

PROTOS_SCROLLS_ARCANE_LEVEL_1_NECROMANCY = [ \
	 const_proto_scrolls.PROTO_SCROLL_OF_CAUSE_FEAR \
	, const_proto_scrolls.PROTO_SCROLL_OF_CHILL_TOUCH \
	, const_proto_scrolls.PROTO_SCROLL_OF_RAY_OF_ENFEEBLEMENT\
	, ]

PROTOS_SCROLLS_ARCANE_LEVEL_1_TRANSMUTATION = [ \
	 const_proto_scrolls.PROTO_SCROLL_OF_ENLARGE_PERSON \
	, const_proto_scrolls.PROTO_SCROLL_OF_EXPEDITIOUS_RETREAT \
	, const_proto_scrolls.PROTO_SCROLL_OF_MAGIC_WEAPON \
	, const_proto_scrolls.PROTO_SCROLL_OF_RAY_OF_CLUMSINESS \
	, const_proto_scrolls.PROTO_SCROLL_OF_REDUCE_PERSON\
	, ]

PROTOS_WANDS_ARCANE_LEVEL_1 =  \
	 PROTOS_SCROLLS_ARCANE_LEVEL_1_ABJURATION \
	+ PROTOS_SCROLLS_ARCANE_LEVEL_1_CONJURATION \
	+ PROTOS_SCROLLS_ARCANE_LEVEL_1_DIVINATION \
	+ PROTOS_SCROLLS_ARCANE_LEVEL_1_ENCHANTMENT \
	+ PROTOS_SCROLLS_ARCANE_LEVEL_1_EVOCATION \
	+ PROTOS_SCROLLS_ARCANE_LEVEL_1_ILLUSION \
	+ PROTOS_SCROLLS_ARCANE_LEVEL_1_NECROMANCY \
	+ PROTOS_SCROLLS_ARCANE_LEVEL_1_TRANSMUTATION

PROTOS_SCROLLS_DIVINE_LEVEL_1_ABJURATION = [ \
	 const_proto_scrolls.PROTO_SCROLL_OF_ENTROPIC_SHIELD \
	, const_proto_scrolls.PROTO_SCROLL_OF_HIDE_FROM_ANIMALS \
	, const_proto_scrolls.PROTO_SCROLL_OF_HIDE_FROM_UNDEAD \
	, const_proto_scrolls.PROTO_SCROLL_OF_SANCTUARY \
	, const_proto_scrolls.PROTO_SCROLL_OF_SHIELD_OF_FAITH\
	, ]

PROTOS_SCROLLS_DIVINE_LEVEL_1_CONJURATION = [ \
	 const_proto_scrolls.PROTO_SCROLL_OF_CURE_LIGHT_WOUNDS \
	, const_proto_scrolls.PROTO_SCROLL_OF_SUMMON_NATURES_ALLY_I\
	, ]

PROTOS_SCROLLS_DIVINE_LEVEL_1_DIVINATION = [ \
	 const_proto_scrolls.PROTO_SCROLL_OF_DETECT_CHAOS \
	, const_proto_scrolls.PROTO_SCROLL_OF_DETECT_EVIL \
	, const_proto_scrolls.PROTO_SCROLL_OF_DETECT_GOOD \
	, const_proto_scrolls.PROTO_SCROLL_OF_DETECT_LAW\
	, ]

PROTOS_SCROLLS_DIVINE_LEVEL_1_ENCHANTMENT = [ \
	 const_proto_scrolls.PROTO_SCROLL_OF_BANE \
	, const_proto_scrolls.PROTO_SCROLL_OF_BLESS \
	, const_proto_scrolls.PROTO_SCROLL_OF_CALM_ANIMALS \
	, const_proto_scrolls.PROTO_SCROLL_OF_CHARM_ANIMAL \
	, const_proto_scrolls.PROTO_SCROLL_OF_COMMAND\
	, ]

PROTOS_SCROLLS_DIVINE_LEVEL_1_EVOCATION = [ \
	 const_proto_scrolls.PROTO_SCROLL_OF_DIVINE_FAVOR \
	, const_proto_scrolls.PROTO_SCROLL_OF_FAERIE_FIRE \
	, const_proto_scrolls.PROTO_SCROLL_OF_PRODUCE_FLAME\
	, ]

PROTOS_SCROLLS_DIVINE_LEVEL_1_ILLUSION = []

PROTOS_SCROLLS_DIVINE_LEVEL_1_NECROMANCY = [ \
	 const_proto_scrolls.PROTO_SCROLL_OF_DOOM \
	, const_proto_scrolls.PROTO_SCROLL_OF_INFLICT_LIGHT_WOUNDS\
	, ]

PROTOS_SCROLLS_DIVINE_LEVEL_1_TRANSMUTATION = [ \
	 const_proto_scrolls.PROTO_SCROLL_OF_BLESS_WATER \
	, const_proto_scrolls.PROTO_SCROLL_OF_CURSE_WATER \
	, const_proto_scrolls.PROTO_SCROLL_OF_ENTANGLE \
	, const_proto_scrolls.PROTO_SCROLL_OF_GOODBERRY \
	, const_proto_scrolls.PROTO_SCROLL_OF_LONGSTRIDER \
	, const_proto_scrolls.PROTO_SCROLL_OF_MAGIC_FANG \
	, const_proto_scrolls.PROTO_SCROLL_OF_MAGIC_STONE \
	, const_proto_scrolls.PROTO_SCROLL_OF_SHILLELAGH\
	, ]

PROTOS_WANDS_DIVINE_LEVEL_1 =  \
	 PROTOS_SCROLLS_DIVINE_LEVEL_1_ABJURATION \
	+ PROTOS_SCROLLS_DIVINE_LEVEL_1_CONJURATION \
	+ PROTOS_SCROLLS_DIVINE_LEVEL_1_DIVINATION \
	+ PROTOS_SCROLLS_DIVINE_LEVEL_1_ENCHANTMENT \
	+ PROTOS_SCROLLS_DIVINE_LEVEL_1_EVOCATION \
	+ PROTOS_SCROLLS_DIVINE_LEVEL_1_ILLUSION \
	+ PROTOS_SCROLLS_DIVINE_LEVEL_1_NECROMANCY \
	+ PROTOS_SCROLLS_DIVINE_LEVEL_1_TRANSMUTATION

PROTOS_SCROLLS_ARCANE_LEVEL_2_ABJURATION = [ \
	 const_proto_scrolls.PROTO_SCROLL_OF_PROTECTION_FROM_ARROWS \
	, const_proto_scrolls.PROTO_SCROLL_OF_RESIST_ENERGY\
	, ]

PROTOS_SCROLLS_ARCANE_LEVEL_2_CONJURATION = [ \
	 const_proto_scrolls.PROTO_SCROLL_OF_FOG_CLOUD \
	, const_proto_scrolls.PROTO_SCROLL_OF_GLITTERDUST \
	, const_proto_scrolls.PROTO_SCROLL_OF_MELFS_ACID_ARROW \
	, const_proto_scrolls.PROTO_SCROLL_OF_SUMMON_MONSTER_II \
	, const_proto_scrolls.PROTO_SCROLL_OF_WEB\
	, ]

PROTOS_SCROLLS_ARCANE_LEVEL_2_DIVINATION = [ \
	 const_proto_scrolls.PROTO_SCROLL_OF_SEE_INVISIBILITY\
	, ]

PROTOS_SCROLLS_ARCANE_LEVEL_2_ENCHANTMENT = [ \
	 const_proto_scrolls.PROTO_SCROLL_OF_ANIMAL_TRANCE \
	, const_proto_scrolls.PROTO_SCROLL_OF_CALM_EMOTIONS \
	, const_proto_scrolls.PROTO_SCROLL_OF_DAZE_MONSTER \
	, const_proto_scrolls.PROTO_SCROLL_OF_TASHAS_HIDEOUS_LAUGHTER\
	, ]

PROTOS_SCROLLS_ARCANE_LEVEL_2_EVOCATION = [ \
	 const_proto_scrolls.PROTO_SCROLL_OF_GUST_OF_WIND \
	, const_proto_scrolls.PROTO_SCROLL_OF_SCORCHING_RAY \
	, const_proto_scrolls.PROTO_SCROLL_OF_SHATTER \
	, const_proto_scrolls.PROTO_SCROLL_OF_SOUND_BURST\
	, ]

PROTOS_SCROLLS_ARCANE_LEVEL_2_ILLUSION = [ \
	 const_proto_scrolls.PROTO_SCROLL_OF_BLUR \
	, const_proto_scrolls.PROTO_SCROLL_OF_INVISIBILITY \
	, const_proto_scrolls.PROTO_SCROLL_OF_MIRROR_IMAGE \
	, const_proto_scrolls.PROTO_SCROLL_OF_SILENCE\
	, ]

PROTOS_SCROLLS_ARCANE_LEVEL_2_NECROMANCY = [ \
	 const_proto_scrolls.PROTO_SCROLL_OF_BLINDNESS_DEAFNESS \
	, const_proto_scrolls.PROTO_SCROLL_OF_FALSE_LIFE \
	, const_proto_scrolls.PROTO_SCROLL_OF_GHOUL_TOUCH \
	, const_proto_scrolls.PROTO_SCROLL_OF_SCARE\
	, ]

PROTOS_SCROLLS_ARCANE_LEVEL_2_TRANSMUTATION = [ \
	 const_proto_scrolls.PROTO_SCROLL_OF_BEARS_ENDURANCE \
	, const_proto_scrolls.PROTO_SCROLL_OF_BULLS_STRENGTH \
	, const_proto_scrolls.PROTO_SCROLL_OF_CATS_GRACE \
	, const_proto_scrolls.PROTO_SCROLL_OF_EAGLES_SPLENDOR \
	, const_proto_scrolls.PROTO_SCROLL_OF_FOXS_CUNNING \
	, const_proto_scrolls.PROTO_SCROLL_OF_KNOCK \
	, const_proto_scrolls.PROTO_SCROLL_OF_OWLS_WISDOM\
	, ]

PROTOS_WANDS_ARCANE_LEVEL_2 =  \
	 PROTOS_SCROLLS_ARCANE_LEVEL_2_ABJURATION \
	+ PROTOS_SCROLLS_ARCANE_LEVEL_2_CONJURATION \
	+ PROTOS_SCROLLS_ARCANE_LEVEL_2_DIVINATION \
	+ PROTOS_SCROLLS_ARCANE_LEVEL_2_ENCHANTMENT \
	+ PROTOS_SCROLLS_ARCANE_LEVEL_2_EVOCATION \
	+ PROTOS_SCROLLS_ARCANE_LEVEL_2_ILLUSION \
	+ PROTOS_SCROLLS_ARCANE_LEVEL_2_NECROMANCY \
	+ PROTOS_SCROLLS_ARCANE_LEVEL_2_TRANSMUTATION

PROTOS_SCROLLS_DIVINE_LEVEL_2_ABJURATION = []

PROTOS_SCROLLS_DIVINE_LEVEL_2_CONJURATION = [ \
	 const_proto_scrolls.PROTO_SCROLL_OF_CURE_MODERATE_WOUNDS \
	, const_proto_scrolls.PROTO_SCROLL_OF_DELAY_POISON \
	, const_proto_scrolls.PROTO_SCROLL_OF_RESTORATION_LESSER \
	, const_proto_scrolls.PROTO_SCROLL_OF_REMOVE_PARALYSIS \
	, const_proto_scrolls.PROTO_SCROLL_OF_SUMMON_NATURES_ALLY_II\
	, ]

PROTOS_SCROLLS_DIVINE_LEVEL_2_DIVINATION = [ \
	 const_proto_scrolls.PROTO_SCROLL_OF_FIND_TRAPS\
	, ]

PROTOS_SCROLLS_DIVINE_LEVEL_2_ENCHANTMENT = [ \
	 const_proto_scrolls.PROTO_SCROLL_OF_AID \
	, const_proto_scrolls.PROTO_SCROLL_OF_HOLD_ANIMAL\
	, ]

PROTOS_SCROLLS_DIVINE_LEVEL_2_EVOCATION = [ \
	 const_proto_scrolls.PROTO_SCROLL_OF_CONSECRATE \
	, const_proto_scrolls.PROTO_SCROLL_OF_DESECRATE \
	, const_proto_scrolls.PROTO_SCROLL_OF_SPIRITUAL_WEAPON\
	, ]

PROTOS_SCROLLS_DIVINE_LEVEL_2_ILLUSION = []

PROTOS_SCROLLS_DIVINE_LEVEL_2_NECROMANCY = [ \
	 const_proto_scrolls.PROTO_SCROLL_OF_DEATH_KNELL \
	, const_proto_scrolls.PROTO_SCROLL_OF_INFLICT_MODERATE_WOUNDS\
	, ]

PROTOS_SCROLLS_DIVINE_LEVEL_2_TRANSMUTATION = [ \
	 const_proto_scrolls.PROTO_SCROLL_OF_BARKSKIN \
	, const_proto_scrolls.PROTO_SCROLL_OF_CHILL_METAL \
	, const_proto_scrolls.PROTO_SCROLL_OF_HEAT_METAL \
	, const_proto_scrolls.PROTO_SCROLL_OF_REDUCE_ANIMAL \
	, const_proto_scrolls.PROTO_SCROLL_OF_SOFTEN_EARTH_AND_STONE \
	, const_proto_scrolls.PROTO_SCROLL_OF_SPIKE_GROWTH \
	, const_proto_scrolls.PROTO_SCROLL_OF_TREE_SHAPE \
	, const_proto_scrolls.PROTO_SCROLL_OF_WARP_WOOD\
	, ]

PROTOS_WANDS_DIVINE_LEVEL_2 =  \
	 PROTOS_SCROLLS_DIVINE_LEVEL_2_ABJURATION \
	+ PROTOS_SCROLLS_DIVINE_LEVEL_2_CONJURATION \
	+ PROTOS_SCROLLS_DIVINE_LEVEL_2_DIVINATION \
	+ PROTOS_SCROLLS_DIVINE_LEVEL_2_ENCHANTMENT \
	+ PROTOS_SCROLLS_DIVINE_LEVEL_2_EVOCATION \
	+ PROTOS_SCROLLS_DIVINE_LEVEL_2_ILLUSION \
	+ PROTOS_SCROLLS_DIVINE_LEVEL_2_NECROMANCY \
	+ PROTOS_SCROLLS_DIVINE_LEVEL_2_TRANSMUTATION

PROTOS_SCROLLS_ARCANE_LEVEL_3_ABJURATION = [ \
	 const_proto_scrolls.PROTO_SCROLL_OF_DISPEL_MAGIC \
	, const_proto_scrolls.PROTO_SCROLL_OF_MAGIC_CIRCLE_AGAINST_CHAOS \
	, const_proto_scrolls.PROTO_SCROLL_OF_MAGIC_CIRCLE_AGAINST_EVIL \
	, const_proto_scrolls.PROTO_SCROLL_OF_MAGIC_CIRCLE_AGAINST_GOOD \
	, const_proto_scrolls.PROTO_SCROLL_OF_MAGIC_CIRCLE_AGAINST_LAW \
	, const_proto_scrolls.PROTO_SCROLL_OF_PROTECTION_FROM_ENERGY\
	, ]

PROTOS_SCROLLS_ARCANE_LEVEL_3_CONJURATION = [ \
	 const_proto_scrolls.PROTO_SCROLL_OF_SLEET_STORM \
	, const_proto_scrolls.PROTO_SCROLL_OF_STINKING_CLOUD \
	, const_proto_scrolls.PROTO_SCROLL_OF_SUMMON_MONSTER_III\
	, ]

PROTOS_SCROLLS_ARCANE_LEVEL_3_DIVINATION = [ \
	 const_proto_scrolls.PROTO_SCROLL_OF_CLAIRAUDIENCE_CLAIRVOYANCE\
	, ]

PROTOS_SCROLLS_ARCANE_LEVEL_3_ENCHANTMENT = [ \
	 const_proto_scrolls.PROTO_SCROLL_OF_DEEP_SLUMBER \
	, const_proto_scrolls.PROTO_SCROLL_OF_GOOD_HOPE \
	, const_proto_scrolls.PROTO_SCROLL_OF_HEROISM \
	, const_proto_scrolls.PROTO_SCROLL_OF_HOLD_PERSON \
	, const_proto_scrolls.PROTO_SCROLL_OF_RAGE\
	, ]

PROTOS_SCROLLS_ARCANE_LEVEL_3_EVOCATION = [ \
	 const_proto_scrolls.PROTO_SCROLL_OF_FIREBALL \
	, const_proto_scrolls.PROTO_SCROLL_OF_LIGHTNING_BOLT \
	, const_proto_scrolls.PROTO_SCROLL_OF_WIND_WALL\
	, ]

PROTOS_SCROLLS_ARCANE_LEVEL_3_ILLUSION = [ \
	 const_proto_scrolls.PROTO_SCROLL_OF_DISPLACEMENT \
	, const_proto_scrolls.PROTO_SCROLL_OF_INVISIBILITY_SPHERE\
	, ]

PROTOS_SCROLLS_ARCANE_LEVEL_3_NECROMANCY = [ \
	 const_proto_scrolls.PROTO_SCROLL_OF_GENTLE_REPOSE \
	, const_proto_scrolls.PROTO_SCROLL_OF_HALT_UNDEAD \
	, const_proto_scrolls.PROTO_SCROLL_OF_VAMPIRIC_TOUCH\
	, ]

PROTOS_SCROLLS_ARCANE_LEVEL_3_TRANSMUTATION = [ \
	 const_proto_scrolls.PROTO_SCROLL_OF_BLINK \
	, const_proto_scrolls.PROTO_SCROLL_OF_GASEOUS_FORM \
	, const_proto_scrolls.PROTO_SCROLL_OF_GLIBNESS \
	, const_proto_scrolls.PROTO_SCROLL_OF_MAGIC_WEAPON_GREATER \
	, const_proto_scrolls.PROTO_SCROLL_OF_HASTE \
	, const_proto_scrolls.PROTO_SCROLL_OF_KEEN_EDGE \
	, const_proto_scrolls.PROTO_SCROLL_OF_SLOW\
	, ]

PROTOS_WANDS_ARCANE_LEVEL_3 =  \
	 PROTOS_SCROLLS_ARCANE_LEVEL_3_ABJURATION \
	+ PROTOS_SCROLLS_ARCANE_LEVEL_3_CONJURATION \
	+ PROTOS_SCROLLS_ARCANE_LEVEL_3_DIVINATION \
	+ PROTOS_SCROLLS_ARCANE_LEVEL_3_ENCHANTMENT \
	+ PROTOS_SCROLLS_ARCANE_LEVEL_3_EVOCATION \
	+ PROTOS_SCROLLS_ARCANE_LEVEL_3_ILLUSION \
	+ PROTOS_SCROLLS_ARCANE_LEVEL_3_NECROMANCY \
	+ PROTOS_SCROLLS_ARCANE_LEVEL_3_TRANSMUTATION

PROTOS_SCROLLS_DIVINE_LEVEL_3_ABJURATION = [ \
	 const_proto_scrolls.PROTO_SCROLL_OF_NEGATIVE_ENERGY_PROTECTION\
	, ]

PROTOS_SCROLLS_DIVINE_LEVEL_3_CONJURATION = [ \
	 const_proto_scrolls.PROTO_SCROLL_OF_CURE_SERIOUS_WOUNDS \
	, const_proto_scrolls.PROTO_SCROLL_OF_REMOVE_BLINDNESS_DEAFNESS \
	, const_proto_scrolls.PROTO_SCROLL_OF_REMOVE_DISEASE \
	, const_proto_scrolls.PROTO_SCROLL_OF_SUMMON_NATURES_ALLY_III\
	, ]

PROTOS_SCROLLS_DIVINE_LEVEL_3_DIVINATION = []

PROTOS_SCROLLS_DIVINE_LEVEL_3_ENCHANTMENT = [ \
	 const_proto_scrolls.PROTO_SCROLL_OF_DOMINATE_ANIMAL \
	, const_proto_scrolls.PROTO_SCROLL_OF_PRAYER\
	, ]

PROTOS_SCROLLS_DIVINE_LEVEL_3_EVOCATION = [ \
	 const_proto_scrolls.PROTO_SCROLL_OF_CALL_LIGHTNING \
	, const_proto_scrolls.PROTO_SCROLL_OF_INVISIBILITY_PURGE \
	, const_proto_scrolls.PROTO_SCROLL_OF_SEARING_LIGHT\
	, ]

PROTOS_SCROLLS_DIVINE_LEVEL_3_ILLUSION = []

PROTOS_SCROLLS_DIVINE_LEVEL_3_NECROMANCY = [ \
	 const_proto_scrolls.PROTO_SCROLL_OF_INFLICT_SERIOUS_WOUNDS\
	, ]

PROTOS_SCROLLS_DIVINE_LEVEL_3_TRANSMUTATION = [ \
	 const_proto_scrolls.PROTO_SCROLL_OF_MAGIC_FANG__GREATER \
	, const_proto_scrolls.PROTO_SCROLL_OF_MAGIC_VESTMENT \
	, const_proto_scrolls.PROTO_SCROLL_OF_MELD_INTO_STONE \
	, const_proto_scrolls.PROTO_SCROLL_OF_QUENCH\
	, ]

PROTOS_WANDS_DIVINE_LEVEL_3 =  \
	 PROTOS_SCROLLS_DIVINE_LEVEL_3_ABJURATION \
	+ PROTOS_SCROLLS_DIVINE_LEVEL_3_CONJURATION \
	+ PROTOS_SCROLLS_DIVINE_LEVEL_3_DIVINATION \
	+ PROTOS_SCROLLS_DIVINE_LEVEL_3_ENCHANTMENT \
	+ PROTOS_SCROLLS_DIVINE_LEVEL_3_EVOCATION \
	+ PROTOS_SCROLLS_DIVINE_LEVEL_3_ILLUSION \
	+ PROTOS_SCROLLS_DIVINE_LEVEL_3_NECROMANCY \
	+ PROTOS_SCROLLS_DIVINE_LEVEL_3_TRANSMUTATION

PROTOS_SCROLLS_ARCANE_LEVEL_4_ABJURATION = [ \
	 const_proto_scrolls.PROTO_SCROLL_OF_DIMENSIONAL_ANCHOR \
	, const_proto_scrolls.PROTO_SCROLL_OF_FREEDOM_OF_MOVEMENT \
	, const_proto_scrolls.PROTO_SCROLL_OF_GLOBE_OF_INVULNERABILITY_LESSER \
	, const_proto_scrolls.PROTO_SCROLL_OF_REMOVE_CURSE \
	, const_proto_scrolls.PROTO_SCROLL_OF_STONESKIN\
	, ]

PROTOS_SCROLLS_ARCANE_LEVEL_4_CONJURATION = [ \
	 const_proto_scrolls.PROTO_SCROLL_OF_DIMENSION_DOOR \
	, const_proto_scrolls.PROTO_SCROLL_OF_SOLID_FOG \
	, const_proto_scrolls.PROTO_SCROLL_OF_SUMMON_MONSTER_IV\
	, ]

PROTOS_SCROLLS_ARCANE_LEVEL_4_DIVINATION = []

PROTOS_SCROLLS_ARCANE_LEVEL_4_ENCHANTMENT = [ \
	 const_proto_scrolls.PROTO_SCROLL_OF_CHARM_MONSTER \
	, const_proto_scrolls.PROTO_SCROLL_OF_CONFUSION \
	, const_proto_scrolls.PROTO_SCROLL_OF_CRUSHING_DESPAIR\
	, ]

PROTOS_SCROLLS_ARCANE_LEVEL_4_EVOCATION = [ \
	 const_proto_scrolls.PROTO_SCROLL_OF_FIRE_SHIELD \
	, const_proto_scrolls.PROTO_SCROLL_OF_ICE_STORM \
	, const_proto_scrolls.PROTO_SCROLL_OF_OTILUKES_RESILIENT_SPHERE \
	, const_proto_scrolls.PROTO_SCROLL_OF_SHOUT\
	, ]

PROTOS_SCROLLS_ARCANE_LEVEL_4_ILLUSION = [ \
	 const_proto_scrolls.PROTO_SCROLL_OF_INVISIBILITY_GREATER \
	, const_proto_scrolls.PROTO_SCROLL_OF_PHANTASMAL_KILLER\
	, ]

PROTOS_SCROLLS_ARCANE_LEVEL_4_NECROMANCY = [ \
	 const_proto_scrolls.PROTO_SCROLL_OF_ANIMATE_DEAD \
	, const_proto_scrolls.PROTO_SCROLL_OF_BESTOW_CURSE \
	, const_proto_scrolls.PROTO_SCROLL_OF_CONTAGION \
	, const_proto_scrolls.PROTO_SCROLL_OF_FEAR\
	, ]

PROTOS_SCROLLS_ARCANE_LEVEL_4_TRANSMUTATION = []

PROTOS_WANDS_ARCANE_LEVEL_4 =  \
	 PROTOS_SCROLLS_ARCANE_LEVEL_4_ABJURATION \
	+ PROTOS_SCROLLS_ARCANE_LEVEL_4_CONJURATION \
	+ PROTOS_SCROLLS_ARCANE_LEVEL_4_DIVINATION \
	+ PROTOS_SCROLLS_ARCANE_LEVEL_4_ENCHANTMENT \
	+ PROTOS_SCROLLS_ARCANE_LEVEL_4_EVOCATION \
	+ PROTOS_SCROLLS_ARCANE_LEVEL_4_ILLUSION \
	+ PROTOS_SCROLLS_ARCANE_LEVEL_4_NECROMANCY \
	+ PROTOS_SCROLLS_ARCANE_LEVEL_4_TRANSMUTATION

PROTOS_SCROLLS_DIVINE_LEVEL_4_ABJURATION = [ \
	 const_proto_scrolls.PROTO_SCROLL_OF_REPEL_VERMIN\
	, ]

PROTOS_SCROLLS_DIVINE_LEVEL_4_CONJURATION = [ \
	 const_proto_scrolls.PROTO_SCROLL_OF_CURE_CRITICAL_WOUNDS \
	, const_proto_scrolls.PROTO_SCROLL_OF_NEUTRALIZE_POISON \
	, const_proto_scrolls.PROTO_SCROLL_OF_RESTORATION \
	, const_proto_scrolls.PROTO_SCROLL_OF_SUMMON_NATURES_ALLY_IV\
	, ]

PROTOS_SCROLLS_DIVINE_LEVEL_4_DIVINATION = [ \
	 const_proto_scrolls.PROTO_SCROLL_OF_DISCERN_LIES\
	, ]

PROTOS_SCROLLS_DIVINE_LEVEL_4_ENCHANTMENT = []

PROTOS_SCROLLS_DIVINE_LEVEL_4_EVOCATION = [ \
	 const_proto_scrolls.PROTO_SCROLL_OF_CHAOS_HAMMER \
	, const_proto_scrolls.PROTO_SCROLL_OF_DIVINE_POWER \
	, const_proto_scrolls.PROTO_SCROLL_OF_HOLY_SMITE \
	, const_proto_scrolls.PROTO_SCROLL_OF_HOLY_SWORD \
	, const_proto_scrolls.PROTO_SCROLL_OF_ORDERS_WRATH \
	, const_proto_scrolls.PROTO_SCROLL_OF_UNHOLY_BLIGHT\
	, ]

PROTOS_SCROLLS_DIVINE_LEVEL_4_ILLUSION = []

PROTOS_SCROLLS_DIVINE_LEVEL_4_NECROMANCY = [ \
	 const_proto_scrolls.PROTO_SCROLL_OF_DEATH_WARD \
	, const_proto_scrolls.PROTO_SCROLL_OF_INFLICT_CRITICAL_WOUNDS \
	, const_proto_scrolls.PROTO_SCROLL_OF_POISON\
	, ]

PROTOS_SCROLLS_DIVINE_LEVEL_4_TRANSMUTATION = [ \
	 const_proto_scrolls.PROTO_SCROLL_OF_ANIMAL_FRIENDSHIP \
	, const_proto_scrolls.PROTO_SCROLL_OF_CONTROL_PLANTS \
	, const_proto_scrolls.PROTO_SCROLL_OF_EMOTION \
	, const_proto_scrolls.PROTO_SCROLL_OF_GIANT_VERMIN \
	, const_proto_scrolls.PROTO_SCROLL_OF_REINCARNATE \
	, const_proto_scrolls.PROTO_SCROLL_OF_SPIKE_STONES\
	, ]

PROTOS_WANDS_DIVINE_LEVEL_4 =  \
	 PROTOS_SCROLLS_DIVINE_LEVEL_4_ABJURATION \
	+ PROTOS_SCROLLS_DIVINE_LEVEL_4_CONJURATION \
	+ PROTOS_SCROLLS_DIVINE_LEVEL_4_DIVINATION \
	+ PROTOS_SCROLLS_DIVINE_LEVEL_4_ENCHANTMENT \
	+ PROTOS_SCROLLS_DIVINE_LEVEL_4_EVOCATION \
	+ PROTOS_SCROLLS_DIVINE_LEVEL_4_ILLUSION \
	+ PROTOS_SCROLLS_DIVINE_LEVEL_4_NECROMANCY \
	+ PROTOS_SCROLLS_DIVINE_LEVEL_4_TRANSMUTATION

PROTOS_SCROLLS_ARCANE_LEVEL_5_ABJURATION = [ \
	 const_proto_scrolls.PROTO_SCROLL_OF_BREAK_ENCHANTMENT \
	, const_proto_scrolls.PROTO_SCROLL_OF_DISMISSAL\
	, ]

PROTOS_SCROLLS_ARCANE_LEVEL_5_CONJURATION = [ \
	 const_proto_scrolls.PROTO_SCROLL_OF_CLOUDKILL \
	, const_proto_scrolls.PROTO_SCROLL_OF_EXTRAPLANAR_CHEST \
	, const_proto_scrolls.PROTO_SCROLL_OF_MORDENKAINENS_FAITHFUL_HOUND \
	, const_proto_scrolls.PROTO_SCROLL_OF_SUMMON_MONSTER_V \
	, const_proto_scrolls.PROTO_SCROLL_OF_TELEPORT\
	, ]

PROTOS_SCROLLS_ARCANE_LEVEL_5_DIVINATION = []

PROTOS_SCROLLS_ARCANE_LEVEL_5_ENCHANTMENT = [ \
	 const_proto_scrolls.PROTO_SCROLL_OF_DOMINATE_PERSON \
	, const_proto_scrolls.PROTO_SCROLL_OF_FEEBLEMIND \
	, const_proto_scrolls.PROTO_SCROLL_OF_HOLD_MONSTER \
	, const_proto_scrolls.PROTO_SCROLL_OF_MIND_FOG\
	, ]

PROTOS_SCROLLS_ARCANE_LEVEL_5_EVOCATION = [ \
	 const_proto_scrolls.PROTO_SCROLL_OF_CONE_OF_COLD\
	, ]

PROTOS_SCROLLS_ARCANE_LEVEL_5_ILLUSION = []

PROTOS_SCROLLS_ARCANE_LEVEL_5_NECROMANCY = [ \
	 const_proto_scrolls.PROTO_SCROLL_OF_BLIGHT\
	, ]

PROTOS_SCROLLS_ARCANE_LEVEL_5_TRANSMUTATION = [ \
	 const_proto_scrolls.PROTO_SCROLL_OF_ANIMAL_GROWTH\
	, ]

PROTOS_WANDS_ARCANE_LEVEL_5 =  \
	 PROTOS_SCROLLS_ARCANE_LEVEL_5_ABJURATION \
	+ PROTOS_SCROLLS_ARCANE_LEVEL_5_CONJURATION \
	+ PROTOS_SCROLLS_ARCANE_LEVEL_5_DIVINATION \
	+ PROTOS_SCROLLS_ARCANE_LEVEL_5_ENCHANTMENT \
	+ PROTOS_SCROLLS_ARCANE_LEVEL_5_EVOCATION \
	+ PROTOS_SCROLLS_ARCANE_LEVEL_5_ILLUSION \
	+ PROTOS_SCROLLS_ARCANE_LEVEL_5_NECROMANCY \
	+ PROTOS_SCROLLS_ARCANE_LEVEL_5_TRANSMUTATION

PROTOS_SCROLLS_DIVINE_LEVEL_5_ABJURATION = [ \
	 const_proto_scrolls.PROTO_SCROLL_OF_DISPEL_AIR \
	, const_proto_scrolls.PROTO_SCROLL_OF_DISPEL_CHAOS \
	, const_proto_scrolls.PROTO_SCROLL_OF_DISPEL_EARTH \
	, const_proto_scrolls.PROTO_SCROLL_OF_DISPEL_EVIL \
	, const_proto_scrolls.PROTO_SCROLL_OF_DISPEL_FIRE \
	, const_proto_scrolls.PROTO_SCROLL_OF_DISPEL_GOOD \
	, const_proto_scrolls.PROTO_SCROLL_OF_DISPEL_LAW \
	, const_proto_scrolls.PROTO_SCROLL_OF_DISPEL_WATER \
	, const_proto_scrolls.PROTO_SCROLL_OF_SPELL_RESISTANCE\
	, ]

PROTOS_SCROLLS_DIVINE_LEVEL_5_CONJURATION = [ \
	 const_proto_scrolls.PROTO_SCROLL_OF_CURE_LIGHT_WOUNDS_MASS \
	, const_proto_scrolls.PROTO_SCROLL_OF_RAISE_DEAD \
	, const_proto_scrolls.PROTO_SCROLL_OF_SUMMON_NATURES_ALLY_V\
	, ]

PROTOS_SCROLLS_DIVINE_LEVEL_5_DIVINATION = []

PROTOS_SCROLLS_DIVINE_LEVEL_5_ENCHANTMENT = [ \
	 const_proto_scrolls.PROTO_SCROLL_OF_COMMAND_GREATER\
	, ]

PROTOS_SCROLLS_DIVINE_LEVEL_5_EVOCATION = [ \
	 const_proto_scrolls.PROTO_SCROLL_OF_CALL_LIGHTNING_STORM \
	, const_proto_scrolls.PROTO_SCROLL_OF_FLAME_STRIKE\
	, ]

PROTOS_SCROLLS_DIVINE_LEVEL_5_ILLUSION = []

PROTOS_SCROLLS_DIVINE_LEVEL_5_NECROMANCY = [ \
	 const_proto_scrolls.PROTO_SCROLL_OF_INFLICT_LIGHT_WOUNDS_MASS \
	, const_proto_scrolls.PROTO_SCROLL_OF_SLAY_LIVING\
	, ]

PROTOS_SCROLLS_DIVINE_LEVEL_5_TRANSMUTATION = [ \
	 const_proto_scrolls.PROTO_SCROLL_OF_RIGHTEOUS_MIGHT\
	, ]

PROTOS_WANDS_DIVINE_LEVEL_5 =  \
	 PROTOS_SCROLLS_DIVINE_LEVEL_5_ABJURATION \
	+ PROTOS_SCROLLS_DIVINE_LEVEL_5_CONJURATION \
	+ PROTOS_SCROLLS_DIVINE_LEVEL_5_DIVINATION \
	+ PROTOS_SCROLLS_DIVINE_LEVEL_5_ENCHANTMENT \
	+ PROTOS_SCROLLS_DIVINE_LEVEL_5_EVOCATION \
	+ PROTOS_SCROLLS_DIVINE_LEVEL_5_ILLUSION \
	+ PROTOS_SCROLLS_DIVINE_LEVEL_5_NECROMANCY \
	+ PROTOS_SCROLLS_DIVINE_LEVEL_5_TRANSMUTATION

PROTOS_SCROLLS_ARCANE_LEVEL_6_ABJURATION = [ \
	 const_proto_scrolls.PROTO_SCROLL_OF_DISPEL_MAGIC_GREATER\
	, ]

PROTOS_SCROLLS_ARCANE_LEVEL_6_CONJURATION = [ \
	 const_proto_scrolls.PROTO_SCROLL_OF_HEROES_FEAST \
	, const_proto_scrolls.PROTO_SCROLL_OF_SUMMON_MONSTER_VI\
	, ]

PROTOS_SCROLLS_ARCANE_LEVEL_6_DIVINATION = [ \
	 const_proto_scrolls.PROTO_SCROLL_OF_ANALYZE_DWEOMER \
	, const_proto_scrolls.PROTO_SCROLL_OF_TRUE_SEEING\
	, ]

PROTOS_SCROLLS_ARCANE_LEVEL_6_ENCHANTMENT = [ \
	 const_proto_scrolls.PROTO_SCROLL_OF_HEROISM_GREATER\
	, ]

PROTOS_SCROLLS_ARCANE_LEVEL_6_EVOCATION = [ \
	 const_proto_scrolls.PROTO_SCROLL_OF_CHAIN_LIGHTNING\
	, ]

PROTOS_SCROLLS_ARCANE_LEVEL_6_ILLUSION = []

PROTOS_SCROLLS_ARCANE_LEVEL_6_NECROMANCY = [ \
	 const_proto_scrolls.PROTO_SCROLL_OF_CIRCLE_OF_DEATH \
	, const_proto_scrolls.PROTO_SCROLL_OF_EYEBITE \
	, const_proto_scrolls.PROTO_SCROLL_OF_UNDEATH_TO_DEATH\
	, ]

PROTOS_SCROLLS_ARCANE_LEVEL_6_TRANSMUTATION = [ \
	 const_proto_scrolls.PROTO_SCROLL_OF_DISINTEGRATE \
	, const_proto_scrolls.PROTO_SCROLL_OF_BEARS_ENDURANCE_MASS \
	, const_proto_scrolls.PROTO_SCROLL_OF_BULLS_STRENGTH_MASS \
	, const_proto_scrolls.PROTO_SCROLL_OF_CATS_GRACE_MASS \
	, const_proto_scrolls.PROTO_SCROLL_OF_EAGLES_SPLENDOR_MASS \
	, const_proto_scrolls.PROTO_SCROLL_OF_FOXS_CUNNING_MASS \
	, const_proto_scrolls.PROTO_SCROLL_OF_OWLS_WISDOM_MASS \
	, const_proto_scrolls.PROTO_SCROLL_OF_TENSERS_TRANSFORMATION\
	, ]

PROTOS_WANDS_ARCANE_LEVEL_6 =  \
	 PROTOS_SCROLLS_ARCANE_LEVEL_6_ABJURATION \
	+ PROTOS_SCROLLS_ARCANE_LEVEL_6_CONJURATION \
	+ PROTOS_SCROLLS_ARCANE_LEVEL_6_DIVINATION \
	+ PROTOS_SCROLLS_ARCANE_LEVEL_6_ENCHANTMENT \
	+ PROTOS_SCROLLS_ARCANE_LEVEL_6_EVOCATION \
	+ PROTOS_SCROLLS_ARCANE_LEVEL_6_ILLUSION \
	+ PROTOS_SCROLLS_ARCANE_LEVEL_6_NECROMANCY \
	+ PROTOS_SCROLLS_ARCANE_LEVEL_6_TRANSMUTATION

PROTOS_SCROLLS_DIVINE_LEVEL_6_ABJURATION = []

PROTOS_SCROLLS_DIVINE_LEVEL_6_CONJURATION = [ \
	 const_proto_scrolls.PROTO_SCROLL_OF_CURE_MODERATE_WOUNDS_MASS \
	, const_proto_scrolls.PROTO_SCROLL_OF_HEAL \
	, const_proto_scrolls.PROTO_SCROLL_OF_SUMMON_NATURES_ALLY_VI\
	, ]

PROTOS_SCROLLS_DIVINE_LEVEL_6_DIVINATION = []

PROTOS_SCROLLS_DIVINE_LEVEL_6_ENCHANTMENT = []

PROTOS_SCROLLS_DIVINE_LEVEL_6_EVOCATION = []

PROTOS_SCROLLS_DIVINE_LEVEL_6_ILLUSION = []

PROTOS_SCROLLS_DIVINE_LEVEL_6_NECROMANCY = [ \
	 const_proto_scrolls.PROTO_SCROLL_OF_HARM\
	, ]

PROTOS_SCROLLS_DIVINE_LEVEL_6_TRANSMUTATION = []

PROTOS_WANDS_DIVINE_LEVEL_6 =  \
	 PROTOS_SCROLLS_DIVINE_LEVEL_6_ABJURATION \
	+ PROTOS_SCROLLS_DIVINE_LEVEL_6_CONJURATION \
	+ PROTOS_SCROLLS_DIVINE_LEVEL_6_DIVINATION \
	+ PROTOS_SCROLLS_DIVINE_LEVEL_6_ENCHANTMENT \
	+ PROTOS_SCROLLS_DIVINE_LEVEL_6_EVOCATION \
	+ PROTOS_SCROLLS_DIVINE_LEVEL_6_ILLUSION \
	+ PROTOS_SCROLLS_DIVINE_LEVEL_6_NECROMANCY \
	+ PROTOS_SCROLLS_DIVINE_LEVEL_6_TRANSMUTATION

PROTOS_SCROLLS_ARCANE_LEVEL_7_ABJURATION = []

PROTOS_SCROLLS_ARCANE_LEVEL_7_CONJURATION = [ \
	 const_proto_scrolls.PROTO_SCROLL_OF_SUMMON_MONSTER_VII\
	, ]

PROTOS_SCROLLS_ARCANE_LEVEL_7_DIVINATION = []

PROTOS_SCROLLS_ARCANE_LEVEL_7_ENCHANTMENT = [ \
	 const_proto_scrolls.PROTO_SCROLL_OF_HOLD_PERSON_MASS \
	, const_proto_scrolls.PROTO_SCROLL_OF_INSANITY \
	, const_proto_scrolls.PROTO_SCROLL_OF_POWER_WORD_BLIND\
	, ]

PROTOS_SCROLLS_ARCANE_LEVEL_7_EVOCATION = [ \
	 const_proto_scrolls.PROTO_SCROLL_OF_DELAYED_BLAST_FIREBALL \
	, const_proto_scrolls.PROTO_SCROLL_OF_MORDENKAINENS_SWORD \
	, const_proto_scrolls.PROTO_SCROLL_OF_PRISMATIC_SPRAY\
	, ]

PROTOS_SCROLLS_ARCANE_LEVEL_7_ILLUSION = []

PROTOS_SCROLLS_ARCANE_LEVEL_7_NECROMANCY = [ \
	 const_proto_scrolls.PROTO_SCROLL_OF_FINGER_OF_DEATH\
	, ]

PROTOS_SCROLLS_ARCANE_LEVEL_7_TRANSMUTATION = []

PROTOS_WANDS_ARCANE_LEVEL_7 =  \
	 PROTOS_SCROLLS_ARCANE_LEVEL_7_ABJURATION \
	+ PROTOS_SCROLLS_ARCANE_LEVEL_7_CONJURATION \
	+ PROTOS_SCROLLS_ARCANE_LEVEL_7_DIVINATION \
	+ PROTOS_SCROLLS_ARCANE_LEVEL_7_ENCHANTMENT \
	+ PROTOS_SCROLLS_ARCANE_LEVEL_7_EVOCATION \
	+ PROTOS_SCROLLS_ARCANE_LEVEL_7_ILLUSION \
	+ PROTOS_SCROLLS_ARCANE_LEVEL_7_NECROMANCY \
	+ PROTOS_SCROLLS_ARCANE_LEVEL_7_TRANSMUTATION

PROTOS_SCROLLS_DIVINE_LEVEL_7_ABJURATION = []

PROTOS_SCROLLS_DIVINE_LEVEL_7_CONJURATION = [ \
	 const_proto_scrolls.PROTO_SCROLL_OF_CURE_SERIOUS_WOUNDS_MASS \
	, const_proto_scrolls.PROTO_SCROLL_OF_SUMMON_NATURES_ALLY_VII\
	, ]

PROTOS_SCROLLS_DIVINE_LEVEL_7_DIVINATION = []

PROTOS_SCROLLS_DIVINE_LEVEL_7_ENCHANTMENT = []

PROTOS_SCROLLS_DIVINE_LEVEL_7_EVOCATION = [ \
	 const_proto_scrolls.PROTO_SCROLL_OF_BLASPHEMY \
	, const_proto_scrolls.PROTO_SCROLL_OF_HOLY_WORD\
	, ]

PROTOS_SCROLLS_DIVINE_LEVEL_7_ILLUSION = []

PROTOS_SCROLLS_DIVINE_LEVEL_7_NECROMANCY = [ \
	 const_proto_scrolls.PROTO_SCROLL_OF_INFLICT_SERIOUS_WOUNDS_MASS\
	, ]

PROTOS_SCROLLS_DIVINE_LEVEL_7_TRANSMUTATION = []

PROTOS_WANDS_DIVINE_LEVEL_7 =  \
	 PROTOS_SCROLLS_DIVINE_LEVEL_7_ABJURATION \
	+ PROTOS_SCROLLS_DIVINE_LEVEL_7_CONJURATION \
	+ PROTOS_SCROLLS_DIVINE_LEVEL_7_DIVINATION \
	+ PROTOS_SCROLLS_DIVINE_LEVEL_7_ENCHANTMENT \
	+ PROTOS_SCROLLS_DIVINE_LEVEL_7_EVOCATION \
	+ PROTOS_SCROLLS_DIVINE_LEVEL_7_ILLUSION \
	+ PROTOS_SCROLLS_DIVINE_LEVEL_7_NECROMANCY \
	+ PROTOS_SCROLLS_DIVINE_LEVEL_7_TRANSMUTATION

PROTOS_SCROLLS_ARCANE_LEVEL_8_ABJURATION = []

PROTOS_SCROLLS_ARCANE_LEVEL_8_CONJURATION = [ \
	 const_proto_scrolls.PROTO_SCROLL_OF_SUMMON_MONSTER_VIII\
	, ]

PROTOS_SCROLLS_ARCANE_LEVEL_8_DIVINATION = []

PROTOS_SCROLLS_ARCANE_LEVEL_8_ENCHANTMENT = [ \
	 const_proto_scrolls.PROTO_SCROLL_OF_CHARM_MONSTER_MASS \
	, const_proto_scrolls.PROTO_SCROLL_OF_POWER_WORD_STUN\
	, ]

PROTOS_SCROLLS_ARCANE_LEVEL_8_EVOCATION = [ \
	 const_proto_scrolls.PROTO_SCROLL_OF_POLAR_RAY\
	, ]

PROTOS_SCROLLS_ARCANE_LEVEL_8_ILLUSION = []

PROTOS_SCROLLS_ARCANE_LEVEL_8_NECROMANCY = [ \
	 const_proto_scrolls.PROTO_SCROLL_OF_HORRID_WILTING\
	, ]

PROTOS_SCROLLS_ARCANE_LEVEL_8_TRANSMUTATION = []

PROTOS_WANDS_ARCANE_LEVEL_8 =  \
	 PROTOS_SCROLLS_ARCANE_LEVEL_8_ABJURATION \
	+ PROTOS_SCROLLS_ARCANE_LEVEL_8_CONJURATION \
	+ PROTOS_SCROLLS_ARCANE_LEVEL_8_DIVINATION \
	+ PROTOS_SCROLLS_ARCANE_LEVEL_8_ENCHANTMENT \
	+ PROTOS_SCROLLS_ARCANE_LEVEL_8_EVOCATION \
	+ PROTOS_SCROLLS_ARCANE_LEVEL_8_ILLUSION \
	+ PROTOS_SCROLLS_ARCANE_LEVEL_8_NECROMANCY \
	+ PROTOS_SCROLLS_ARCANE_LEVEL_8_TRANSMUTATION

PROTOS_SCROLLS_DIVINE_LEVEL_8_ABJURATION = []

PROTOS_SCROLLS_DIVINE_LEVEL_8_CONJURATION = [ \
	 const_proto_scrolls.PROTO_SCROLL_OF_CURE_CRITICAL_WOUNDS_MASS \
	, const_proto_scrolls.PROTO_SCROLL_OF_SUMMON_NATURES_ALLY_VIII\
	, ]

PROTOS_SCROLLS_DIVINE_LEVEL_8_DIVINATION = []

PROTOS_SCROLLS_DIVINE_LEVEL_8_ENCHANTMENT = []

PROTOS_SCROLLS_DIVINE_LEVEL_8_EVOCATION = []

PROTOS_SCROLLS_DIVINE_LEVEL_8_ILLUSION = []

PROTOS_SCROLLS_DIVINE_LEVEL_8_NECROMANCY = [ \
	 const_proto_scrolls.PROTO_SCROLL_OF_INFLICT_CRITICAL_WOUNDS_MASS\
	, ]

PROTOS_SCROLLS_DIVINE_LEVEL_8_TRANSMUTATION = []

PROTOS_WANDS_DIVINE_LEVEL_8 =  \
	 PROTOS_SCROLLS_DIVINE_LEVEL_8_ABJURATION \
	+ PROTOS_SCROLLS_DIVINE_LEVEL_8_CONJURATION \
	+ PROTOS_SCROLLS_DIVINE_LEVEL_8_DIVINATION \
	+ PROTOS_SCROLLS_DIVINE_LEVEL_8_ENCHANTMENT \
	+ PROTOS_SCROLLS_DIVINE_LEVEL_8_EVOCATION \
	+ PROTOS_SCROLLS_DIVINE_LEVEL_8_ILLUSION \
	+ PROTOS_SCROLLS_DIVINE_LEVEL_8_NECROMANCY \
	+ PROTOS_SCROLLS_DIVINE_LEVEL_8_TRANSMUTATION

PROTOS_SCROLLS_ARCANE_LEVEL_9_ABJURATION = []

PROTOS_SCROLLS_ARCANE_LEVEL_9_CONJURATION = [ \
	 const_proto_scrolls.PROTO_SCROLL_OF_SUMMON_MONSTER_IX\
	, ]

PROTOS_SCROLLS_ARCANE_LEVEL_9_DIVINATION = []

PROTOS_SCROLLS_ARCANE_LEVEL_9_ENCHANTMENT = [ \
	 const_proto_scrolls.PROTO_SCROLL_OF_HOLD_MONSTER_MASS \
	, const_proto_scrolls.PROTO_SCROLL_OF_POWER_WORD_KILL\
	, ]

PROTOS_SCROLLS_ARCANE_LEVEL_9_EVOCATION = []

PROTOS_SCROLLS_ARCANE_LEVEL_9_ILLUSION = [ \
	 const_proto_scrolls.PROTO_SCROLL_OF_WEIRD\
	, ]

PROTOS_SCROLLS_ARCANE_LEVEL_9_NECROMANCY = []

PROTOS_SCROLLS_ARCANE_LEVEL_9_TRANSMUTATION = []

PROTOS_WANDS_ARCANE_LEVEL_9 =  \
	 PROTOS_SCROLLS_ARCANE_LEVEL_9_ABJURATION \
	+ PROTOS_SCROLLS_ARCANE_LEVEL_9_CONJURATION \
	+ PROTOS_SCROLLS_ARCANE_LEVEL_9_DIVINATION \
	+ PROTOS_SCROLLS_ARCANE_LEVEL_9_ENCHANTMENT \
	+ PROTOS_SCROLLS_ARCANE_LEVEL_9_EVOCATION \
	+ PROTOS_SCROLLS_ARCANE_LEVEL_9_ILLUSION \
	+ PROTOS_SCROLLS_ARCANE_LEVEL_9_NECROMANCY \
	+ PROTOS_SCROLLS_ARCANE_LEVEL_9_TRANSMUTATION

PROTOS_SCROLLS_DIVINE_LEVEL_9_ABJURATION = []

PROTOS_SCROLLS_DIVINE_LEVEL_9_CONJURATION = [ \
	 const_proto_scrolls.PROTO_SCROLL_OF_HEAL_MASS \
	, const_proto_scrolls.PROTO_SCROLL_OF_SUMMON_NATURES_ALLY_IX\
	, ]

PROTOS_SCROLLS_DIVINE_LEVEL_9_DIVINATION = []

PROTOS_SCROLLS_DIVINE_LEVEL_9_ENCHANTMENT = []

PROTOS_SCROLLS_DIVINE_LEVEL_9_EVOCATION = [ \
	 const_proto_scrolls.PROTO_SCROLL_OF_MIRACLE\
	, ]

PROTOS_SCROLLS_DIVINE_LEVEL_9_ILLUSION = []

PROTOS_SCROLLS_DIVINE_LEVEL_9_NECROMANCY = []

PROTOS_SCROLLS_DIVINE_LEVEL_9_TRANSMUTATION = []

PROTOS_WANDS_DIVINE_LEVEL_9 =  \
	 PROTOS_SCROLLS_DIVINE_LEVEL_9_ABJURATION \
	+ PROTOS_SCROLLS_DIVINE_LEVEL_9_CONJURATION \
	+ PROTOS_SCROLLS_DIVINE_LEVEL_9_DIVINATION \
	+ PROTOS_SCROLLS_DIVINE_LEVEL_9_ENCHANTMENT \
	+ PROTOS_SCROLLS_DIVINE_LEVEL_9_EVOCATION \
	+ PROTOS_SCROLLS_DIVINE_LEVEL_9_ILLUSION \
	+ PROTOS_SCROLLS_DIVINE_LEVEL_9_NECROMANCY \
	+ PROTOS_SCROLLS_DIVINE_LEVEL_9_TRANSMUTATION

