import const_proto_items

PROTO_INSTRUMENTS = [\
	const_proto_items.PROTO_INSTRUMENT_DRUM \
	, const_proto_items.PROTO_INSTRUMENT_FLUTE \
	, const_proto_items.PROTO_INSTRUMENT_HORN \
	, const_proto_items.PROTO_INSTRUMENT_MANDOLIN \
	]

PROTO_INSTRUMENTS_MASTERWORK = [\
	const_proto_items.PROTO_INSTRUMENT_DRUM_MASTERWORK \
	, const_proto_items.PROTO_INSTRUMENT_FLUTE_MASTERWORK \
	, const_proto_items.PROTO_INSTRUMENT_HORN_MASTERWORK \
	, const_proto_items.PROTO_INSTRUMENT_MANDOLIN_MASTERWORK \
	]

PROTO_INSTRUMENTS_ALL = PROTO_INSTRUMENTS + PROTO_INSTRUMENTS_MASTERWORK
