import const_proto_armor

PROTOS_ARMOR_LIGHT_PADDED = [\
	const_proto_armor.PROTO_ARMOR_PADDED_ARMOR_TAN \
	, const_proto_armor.PROTO_ARMOR_PADDED_ARMOR_RED \
	]

PROTOS_ARMOR_LIGHT_LEATHER = [\
	const_proto_armor.PROTO_ARMOR_LEATHER_ARMOR_BROWN \
	, const_proto_armor.PROTO_ARMOR_LEATHER_ARMOR_BLACK \
	, const_proto_armor.PROTO_ARMOR_LEATHER_ARMOR_TAN \
	, const_proto_armor.PROTO_ARMOR_LEATHER_ARMOR_GREY \
	]

PROTOS_ARMOR_LIGHT_STUDDED = [\
	const_proto_armor.PROTO_ARMOR_STUDDED_LEATHER_ARMOR \
	, ]

PROTOS_ARMOR_LIGHT_CHAIN_SHIRT = [\
	const_proto_armor.PROTO_ARMOR_CHAIN_SHIRT \
	, ]

PROTOS_ARMOR_LEATHER = PROTOS_ARMOR_LIGHT_PADDED + PROTOS_ARMOR_LIGHT_LEATHER + PROTOS_ARMOR_LIGHT_STUDDED
PROTOS_ARMOR_LIGHT = PROTOS_ARMOR_LIGHT_PADDED + PROTOS_ARMOR_LIGHT_LEATHER + PROTOS_ARMOR_LIGHT_STUDDED + PROTOS_ARMOR_LIGHT_CHAIN_SHIRT

PROTOS_ARMOR_MEDIUM_HIDE = [\
	const_proto_armor.PROTO_ARMOR_HIDE \
	, ]

PROTOS_ARMOR_MEDIUM_SCALE = [\
	const_proto_armor.PROTO_ARMOR_SCALE_MAIL \
	, const_proto_armor.PROTO_ARMOR_SCALE_MAIL_FINE \
	, ]

PROTOS_ARMOR_MEDIUM_CHAINMAIL = [\
	const_proto_armor.PROTO_ARMOR_CHAINMAIL \
	, const_proto_armor.PROTO_ARMOR_CHAINMAIL_FINE \
	, const_proto_armor.PROTO_ARMOR_CHAINMAIL_RED \
	, const_proto_armor.PROTO_ARMOR_CHAINMAIL_GOLD \
	, ]

PROTOS_ARMOR_MEDIUM_BREASTPLATE = [\
	const_proto_armor.PROTO_ARMOR_BREASTPLATE \
	, const_proto_armor.PROTO_ARMOR_BREASTPLATE_BLACK \
	, const_proto_armor.PROTO_ARMOR_BREASTPLATE_GOLD
	, ]

PROTOS_ARMOR_MEDIUM = PROTOS_ARMOR_MEDIUM_HIDE + PROTOS_ARMOR_MEDIUM_SCALE + PROTOS_ARMOR_MEDIUM_CHAINMAIL + PROTOS_ARMOR_MEDIUM_BREASTPLATE

PROTOS_ARMOR_HEAVY_SPLINT_MAIL = [\
	const_proto_armor.PROTO_ARMOR_SPLINT_MAIL \
	, ]

PROTOS_ARMOR_HEAVY_BANDED_MAIL = [\
	const_proto_armor.PROTO_ARMOR_BANDED_MAIL \
	, const_proto_armor.PROTO_ARMOR_BANDED_MAIL_BLACK \
	, ]

PROTOS_ARMOR_HEAVY_HALF_PLATE = [\
	const_proto_armor.PROTO_ARMOR_HALF_PLATE \
	, ]

PROTOS_ARMOR_HEAVY_FULL_PLATE = [\
	const_proto_armor.PROTO_ARMOR_FULL_PLATE \
	, ]

PROTOS_ARMOR_HEAVY = PROTOS_ARMOR_HEAVY_SPLINT_MAIL + PROTOS_ARMOR_HEAVY_BANDED_MAIL + PROTOS_ARMOR_HEAVY_HALF_PLATE + PROTOS_ARMOR_HEAVY_FULL_PLATE

PROTOS_ARMOR = PROTOS_ARMOR_LIGHT + PROTOS_ARMOR_MEDIUM + PROTOS_ARMOR_HEAVY
#============================================
#_MASTERWORK
PROTOS_ARMOR_LIGHT_PADDED_MASTERWORK = [\
	const_proto_armor.PROTO_ARMOR_PADDED_ARMOR_MASTERWORK \
	]

PROTOS_ARMOR_LIGHT_LEATHER_MASTERWORK = [\
	const_proto_armor.PROTO_ARMOR_LEATHER_ARMOR_MASTERWORK \
	, const_proto_armor.PROTO_ARMOR_LEATHER_ARMOR_MASTERWORK_BRIGAND \
	]

PROTOS_ARMOR_LIGHT_STUDDED_MASTERWORK = [\
	const_proto_armor.PROTO_ARMOR_STUDDED_LEATHER_ARMOR_MASTERWORK \
	, ]

PROTOS_ARMOR_LIGHT_CHAIN_SHIRT_MASTERWORK = [\
	const_proto_armor.PROTO_ARMOR_CHAIN_SHIRT_MASTERWORK \
	, const_proto_armor.PROTO_ARMOR_MITHRAL_SHIRT
	, ]

PROTOS_ARMOR_LEATHER_MASTERWORK = PROTOS_ARMOR_LIGHT_PADDED_MASTERWORK + PROTOS_ARMOR_LIGHT_LEATHER_MASTERWORK + PROTOS_ARMOR_LIGHT_STUDDED_MASTERWORK
PROTOS_ARMOR_LIGHT_MASTERWORK = PROTOS_ARMOR_LIGHT_PADDED_MASTERWORK + PROTOS_ARMOR_LIGHT_LEATHER_MASTERWORK + PROTOS_ARMOR_LIGHT_STUDDED_MASTERWORK + PROTOS_ARMOR_LIGHT_CHAIN_SHIRT_MASTERWORK

PROTOS_ARMOR_MEDIUM_HIDE_MASTERWORK = [\
	const_proto_armor.PROTO_ARMOR_HIDE_MASTERWORK \
	, ]

PROTOS_ARMOR_MEDIUM_SCALE_MASTERWORK = [\
	const_proto_armor.PROTO_ARMOR_SCALE_MAIL_MASTERWORK\
	, ]

PROTOS_ARMOR_MEDIUM_CHAINMAIL_MASTERWORK = [\
	const_proto_armor.PROTO_ARMOR_CHAINMAIL_MASTERWORK_FINE \
	, const_proto_armor.PROTO_ARMOR_CHAINMAIL_MASTERWORK_RED \
	, ]

PROTOS_ARMOR_MEDIUM_BREASTPLATE_MASTERWORK = [\
	const_proto_armor.PROTO_ARMOR_BREASTPLATE_MASTERWORK \
	, ]

PROTOS_ARMOR_MEDIUM_MASTERWORK = PROTOS_ARMOR_MEDIUM_HIDE_MASTERWORK + PROTOS_ARMOR_MEDIUM_SCALE_MASTERWORK + PROTOS_ARMOR_MEDIUM_CHAINMAIL_MASTERWORK + PROTOS_ARMOR_MEDIUM_BREASTPLATE_MASTERWORK

PROTOS_ARMOR_HEAVY_SPLINT_MAIL_MASTERWORK = [\
	const_proto_armor.PROTO_ARMOR_SPLINT_MAIL_MASTERWORK \
	, ]

PROTOS_ARMOR_HEAVY_BANDED_MAIL_MASTERWORK = [\
	const_proto_armor.PROTO_ARMOR_BANDED_MAIL_MASTERWORK \
	, ]

PROTOS_ARMOR_HEAVY_HALF_PLATE_MASTERWORK = [\
	const_proto_armor.PROTO_ARMOR_HALF_PLATE_MASTERWORK \
	, ]

PROTOS_ARMOR_HEAVY_FULL_PLATE_MASTERWORK = [\
	const_proto_armor.PROTO_ARMOR_FULL_PLATE_MASTERWORK \
	, const_proto_armor.PROTO_ARMOR_FULL_PLATE_MITHRAL
	, ]

PROTOS_ARMOR_HEAVY_MASTERWORK = PROTOS_ARMOR_HEAVY_SPLINT_MAIL_MASTERWORK + PROTOS_ARMOR_HEAVY_BANDED_MAIL_MASTERWORK + PROTOS_ARMOR_HEAVY_HALF_PLATE_MASTERWORK + PROTOS_ARMOR_HEAVY_FULL_PLATE_MASTERWORK

PROTOS_ARMOR_MASTERWORK = PROTOS_ARMOR_LIGHT_MASTERWORK + PROTOS_ARMOR_MEDIUM_MASTERWORK + PROTOS_ARMOR_HEAVY_MASTERWORK
#============================================
#_PLUS_1
PROTOS_ARMOR_LIGHT_PADDED_PLUS_1 = []
PROTOS_ARMOR_LIGHT_LEATHER_PLUS_1 = [\
	const_proto_armor.PROTO_ARMOR_LEATHER_ARMOR_PLUS_1_BROWN \
	, const_proto_armor.PROTO_ARMOR_LEATHER_ARMOR_PLUS_1_BLACK \
	, const_proto_armor.PROTO_ARMOR_LEATHER_ARMOR_PLUS_1_TAN \
	]

PROTOS_ARMOR_LIGHT_STUDDED_PLUS_1 = [\
	const_proto_armor.PROTO_ARMOR_STUDDED_LEATHER_ARMOR_PLUS_1 \
	, ]

PROTOS_ARMOR_LIGHT_CHAIN_SHIRT_PLUS_1 = [\
	const_proto_armor.PROTO_ARMOR_CHAIN_SHIRT_PLUS_1 \
	, const_proto_armor.PROTO_ARMOR_CHAIN_ELVEN_GREEN \
	, ]

PROTOS_ARMOR_LEATHER_PLUS_1 = PROTOS_ARMOR_LIGHT_PADDED_PLUS_1 + PROTOS_ARMOR_LIGHT_LEATHER_PLUS_1 + PROTOS_ARMOR_LIGHT_STUDDED_PLUS_1
PROTOS_ARMOR_LIGHT_PLUS_1 = PROTOS_ARMOR_LIGHT_PADDED_PLUS_1 + PROTOS_ARMOR_LIGHT_LEATHER_PLUS_1 + PROTOS_ARMOR_LIGHT_STUDDED_PLUS_1 + PROTOS_ARMOR_LIGHT_CHAIN_SHIRT_PLUS_1

PROTOS_ARMOR_MEDIUM_HIDE_PLUS_1 = []
PROTOS_ARMOR_MEDIUM_SCALE_PLUS_1 = []

PROTOS_ARMOR_MEDIUM_CHAINMAIL_PLUS_1 = [\
	const_proto_armor.PROTO_ARMOR_CHAINMAIL_PLUS_1 \
	, ]

PROTOS_ARMOR_MEDIUM_BREASTPLATE_PLUS_1 = [\
	const_proto_armor.PROTO_ARMOR_BREASTPLATE_PLUS_1 \
	, const_proto_armor.PROTO_ARMOR_BREASTPLATE_PLUS_1_BLACK \
	, ]

PROTOS_ARMOR_MEDIUM_PLUS_1 = PROTOS_ARMOR_MEDIUM_HIDE_PLUS_1 + PROTOS_ARMOR_MEDIUM_SCALE_PLUS_1 + PROTOS_ARMOR_MEDIUM_CHAINMAIL_PLUS_1 + PROTOS_ARMOR_MEDIUM_BREASTPLATE_PLUS_1

PROTOS_ARMOR_HEAVY_SPLINT_MAIL_PLUS_1 = []

PROTOS_ARMOR_HEAVY_BANDED_MAIL_PLUS_1 = [\
	const_proto_armor.PROTO_ARMOR_BANDED_MAIL_PLUS_1 \
	, const_proto_armor.PROTO_ARMOR_BANDED_MAIL_PLUS_1_BLACK \
	, ]

PROTOS_ARMOR_HEAVY_HALF_PLATE_PLUS_1 = []

PROTOS_ARMOR_HEAVY_FULL_PLATE_PLUS_1 = [\
	const_proto_armor.PROTO_ARMOR_FULL_PLATE_PLUS_1 \
	, const_proto_armor.PROTO_ARMOR_FULL_PLATE_PLUS_1_BLACK \
	, ]

PROTOS_ARMOR_HEAVY_PLUS_1 = PROTOS_ARMOR_HEAVY_SPLINT_MAIL_PLUS_1 + PROTOS_ARMOR_HEAVY_BANDED_MAIL_PLUS_1 + PROTOS_ARMOR_HEAVY_HALF_PLATE_PLUS_1 + PROTOS_ARMOR_HEAVY_FULL_PLATE_PLUS_1
PROTOS_ARMOR_PLUS_1 = PROTOS_ARMOR_LIGHT_PLUS_1 + PROTOS_ARMOR_MEDIUM_PLUS_1 + PROTOS_ARMOR_HEAVY_PLUS_1
#============================================
#_PLUS_2
PROTOS_ARMOR_PLUS_2 = [const_proto_armor.PROTO_ARMOR_CHAINMAIL_PLUS_2_RED, const_proto_armor.PROTO_ARMOR_CHAIN_ELVEN_PURPLE]

#============================================
#_PLUS_3
PROTOS_ARMOR_PLUS_3 = [\
	const_proto_armor.PROTO_ARMOR_LEATHER_ARMOR_PLUS_3_BROWN \
	, const_proto_armor.PROTO_ARMOR_CHAIN_ELVEN_BLUE
	, const_proto_armor.PROTO_ARMOR_CHAIN_SHIRT_PLUS_3 \
	, const_proto_armor.PROTO_ARMOR_CHAINMAIL_PLUS_3_RED
	, ]

PROTOS_ARMOR_MAGIC = PROTOS_ARMOR_PLUS_1 + PROTOS_ARMOR_PLUS_2 + PROTOS_ARMOR_PLUS_3

#============================================
#SHIELD

PROTOS_SHIELD_BUCKLER = [\
	const_proto_armor.PROTO_SHIELD_BUCKLER \
	, ]

PROTOS_SHIELD_SMALL_WOODEN = [\
	const_proto_armor.PROTO_SHIELD_SMALL_WOODEN \
	, ]

PROTOS_SHIELD_SMALL_STEEL = [\
	const_proto_armor.PROTO_SHIELD_SMALL_STEEL \
	, const_proto_armor.PROTO_SHIELD_SMALL_STEEL_2 \
	, ]

PROTOS_SHIELD_SMALL = PROTOS_SHIELD_SMALL_WOODEN + PROTOS_SHIELD_SMALL_STEEL

PROTOS_SHIELD_LARGE_WOODEN = [\
	const_proto_armor.PROTO_SHIELD_LARGE_WOODEN \
	, const_proto_armor.PROTO_SHIELD_LARGE_WOODEN_2 \
	, const_proto_armor.PROTO_SHIELD_LARGE_WOODEN_3 \
	, const_proto_armor.PROTO_SHIELD_LARGE_WOODEN_4 \
	, const_proto_armor.PROTO_SHIELD_LARGE_WOODEN_SPIKED \
	, ]

PROTOS_SHIELD_LARGE_STEEL = [\
	const_proto_armor.PROTO_SHIELD_LARGE_STEEL \
	, const_proto_armor.PROTO_SHIELD_LARGE_STEEL_2 \
	, const_proto_armor.PROTO_SHIELD_LARGE_STEEL_3 \
	, const_proto_armor.PROTO_SHIELD_LARGE_STEEL_4 \
	, ]

PROTOS_SHIELD_LARGE = PROTOS_SHIELD_LARGE_WOODEN + PROTOS_SHIELD_LARGE_STEEL

PROTOS_SHIELD_TOWER_WOODEN = [\
	const_proto_armor.PROTO_SHIELD_TOWER_WOODEN \
	, ]

PROTOS_SHIELD_TOWER_STEEL = [\
	const_proto_armor.PROTO_SHIELD_TOWER_STEEL \
	, ]

PROTOS_SHIELD_TOWER = PROTOS_SHIELD_TOWER_WOODEN + PROTOS_SHIELD_TOWER_STEEL

PROTOS_SHIELDS = PROTOS_SHIELD_BUCKLER + PROTOS_SHIELD_SMALL + PROTOS_SHIELD_LARGE + PROTOS_SHIELD_TOWER

PROTOS_ARMOR_AND_SHIELDS = PROTOS_ARMOR + PROTOS_SHIELDS
#============================================
#SHIELD_MASTERWORK

PROTOS_SHIELD_BUCKLER_MASTERWORK = [\
	const_proto_armor.PROTO_SHIELD_BUCKLER_MASTERWORK \
	, const_proto_armor.PROTO_SHIELD_BUCKLER_MASTERWORK_DARKWOOD \
	, const_proto_armor.PROTO_SHIELD_BUCKLER_MASTERWORK_MITHRAL \
	, ]

PROTOS_SHIELD_SMALL_MASTERWORK_WOODEN = [\
	const_proto_armor.PROTO_SHIELD_SMALL_MASTERWORK_WOODEN \
	, ]

PROTOS_SHIELD_SMALL_MASTERWORK_STEEL = [\
	const_proto_armor.PROTO_SHIELD_SMALL_MASTERWORK_STEEL \
	, ]

PROTOS_SHIELD_SMALL_MASTERWORK = PROTOS_SHIELD_SMALL_WOODEN + PROTOS_SHIELD_SMALL_STEEL

PROTOS_SHIELD_LARGE_MASTERWORK_WOODEN = [\
	const_proto_armor.PROTO_SHIELD_LARGE_MASTERWORK_WOODEN \
	, ]

PROTOS_SHIELD_LARGE_MASTERWORK_STEEL = [\
	const_proto_armor.PROTO_SHIELD_LARGE_MASTERWORK_STEEL \
	, ]

PROTOS_SHIELD_LARGE_MASTERWORK = PROTOS_SHIELD_LARGE_MASTERWORK_WOODEN + PROTOS_SHIELD_LARGE_MASTERWORK_STEEL

PROTOS_SHIELD_TOWER_MASTERWORK_WOODEN = []

PROTOS_SHIELD_TOWER_MASTERWORK_STEEL = [\
	const_proto_armor.PROTO_SHIELD_TOWER_MASTERWORK_STEEL \
	, ]

PROTOS_SHIELD_TOWER_MASTERWORK = PROTOS_SHIELD_TOWER_MASTERWORK_WOODEN + PROTOS_SHIELD_TOWER_MASTERWORK_STEEL

PROTOS_SHIELDS_MASTERWORK = PROTOS_SHIELD_BUCKLER_MASTERWORK + PROTOS_SHIELD_SMALL_MASTERWORK + PROTOS_SHIELD_LARGE_MASTERWORK + PROTOS_SHIELD_TOWER_MASTERWORK

PROTOS_ARMOR_AND_SHIELDS_MASTERWORK = PROTOS_ARMOR_MASTERWORK + PROTOS_SHIELDS_MASTERWORK
#============================================
#SHIELD_PLUS_1

PROTOS_SHIELD_BUCKLER_PLUS_1 = []
PROTOS_SHIELD_SMALL_PLUS_1_WOODEN = []
PROTOS_SHIELD_SMALL_PLUS_1_STEEL = []
PROTOS_SHIELD_SMALL_PLUS_1 = PROTOS_SHIELD_SMALL_WOODEN + PROTOS_SHIELD_SMALL_STEEL

PROTOS_SHIELD_LARGE_PLUS_1_WOODEN = []

PROTOS_SHIELD_LARGE_PLUS_1_STEEL = [\
	const_proto_armor.PROTO_SHIELD_LARGE_PLUS_1_STEEL \
	, ]

PROTOS_SHIELD_LARGE_PLUS_1 = PROTOS_SHIELD_LARGE_PLUS_1_WOODEN + PROTOS_SHIELD_LARGE_PLUS_1_STEEL

PROTOS_SHIELD_TOWER_PLUS_1_WOODEN = []
PROTOS_SHIELD_TOWER_PLUS_1_STEEL = []
PROTOS_SHIELD_TOWER_PLUS_1 = PROTOS_SHIELD_TOWER_PLUS_1_WOODEN + PROTOS_SHIELD_TOWER_PLUS_1_STEEL

PROTOS_SHIELDS_PLUS_1 = PROTOS_SHIELD_SMALL_PLUS_1 + PROTOS_SHIELD_LARGE_PLUS_1 + PROTOS_SHIELD_TOWER_PLUS_1

#============================================
#SHIELD MAGIC
PROTOS_SHIELD_LARGE_MINOR = [\
	const_proto_armor.PROTO_SHIELD_LARGE_PLUS_1_STEEL \
	, const_proto_armor.PROTO_SHIELD_LARGE_PLUS_2_STEEL \
	, const_proto_armor.PROTO_SHIELD_LARGE_PLUS_3_STEEL \
	, ]

PROTOS_SHIELD_LARGE_MEDIUM = [\
	const_proto_armor.PROTO_SHIELD_LARGE_PLUS_3_STEEL \
	, const_proto_armor.PROTO_SHIELD_LARGE_PLUS_4_STEEL \
	, ]

PROTOS_SHIELDS_MAGIC = PROTOS_SHIELD_LARGE_MINOR + PROTOS_SHIELD_LARGE_MEDIUM

PROTOS_ARMOR_AND_SHIELDS_MAGIC = PROTOS_ARMOR_MAGIC + PROTOS_SHIELDS_MAGIC
