import const_proto_cloth

# BOOTS
PROTO_CLOTH_BOOTS_LEATHER = [\
	const_proto_cloth.PROTO_CLOTH_BOOTS_LEATHER_BOOTS_BLACK \
	, const_proto_cloth.PROTO_CLOTH_BOOTS_LEATHER_BOOTS_FINE \
	, const_proto_cloth.PROTO_CLOTH_BOOTS_LEATHER_BOOTS_GREEN \
	, const_proto_cloth.PROTO_CLOTH_BOOTS_LEATHER_BOOTS_WHITE \
	, const_proto_cloth.PROTO_CLOTH_BOOTS_LEATHER_BOOTS_COMBAT \
	, const_proto_cloth.PROTO_CLOTH_BOOTS_LEATHER_BROWN \
	, const_proto_cloth.PROTO_CLOTH_BOOTS_MONK \
	, const_proto_cloth.PROTO_CLOTH_BOOTS_BUCCANEER \
	, const_proto_cloth.PROTO_CLOTH_BOOTS_PADDED_TAN \
	, const_proto_cloth.PROTO_CLOTH_BOOTS_PADDED_RED \
	, ]

PROTO_CLOTH_BOOTS_METAL = [\
	const_proto_cloth.PROTO_CLOTH_BOOTS_CHAINMAIL_BOOTS \
	, const_proto_cloth.PROTO_CLOTH_BOOTS_SILVER_PLATE_BOOTS \
	, const_proto_cloth.PROTO_CLOTH_BOOTS_GILDED_BOOTS \
	, const_proto_cloth.PROTO_CLOTH_BOOTS_GOLD_BOOTS \
	, ]

PROTO_CLOTH_BOOTS = PROTO_CLOTH_BOOTS_LEATHER + PROTO_CLOTH_BOOTS_METAL

# GLOVES
PROTO_CLOTH_GLOVES_LEATHER = [\
	const_proto_cloth.PROTO_CLOTH_GLOVES_LEATHER_BLACK \
	, const_proto_cloth.PROTO_CLOTH_GLOVES_LEATHER_BROWN \
	, const_proto_cloth.PROTO_CLOTH_GLOVES_PADDED_TAN \
	, const_proto_cloth.PROTO_CLOTH_GLOVES_PADDED_RED \
	, ]

PROTO_CLOTH_GLOVES_METAL = [\
	const_proto_cloth.PROTO_CLOTH_GLOVES_CHAINMAIL_GLOVES \
	, const_proto_cloth.PROTO_CLOTH_GLOVES_SILVER_GLOVES \
	, const_proto_cloth.PROTO_CLOTH_GLOVES_GILDED_GLOVES \
	, const_proto_cloth.PROTO_CLOTH_GLOVES_GOLD_GLOVES \
	, ]

PROTO_CLOTH_GLOVES = PROTO_CLOTH_GLOVES_LEATHER + PROTO_CLOTH_GLOVES_METAL

