MAP_ID_SHATERRED_LAB = 5121
SHATERRED_LAB = "shattered_lab"
SHATERRED_LAB_DAEMON_SCRIPT = 6210
SHATERRED_LAB_DAEMON_ID = "G_E5ABE70D_F211_42B3_9822_DA440143228C"

MAP_ID_SHATERRED_TEMPLE = 5123
SHATERRED_TEMPLE = "shattered_temple"
SHATERRED_TEMPLE_DAEMON_ID = "G_53E19CF2_71D2_4F22_A528_5E9BC531B73E"
SHATERRED_TEMPLE_DAEMON_SCRIPT = 6400

MAP_ID_SHATERRED_ARMORY = 5124
SHATERRED_ARMORY = "shattered_armory"
SHATERRED_ARMORY_DAEMON_ID = "G_4FE4AE16_A6DB_4284_943E_49759D5AF434"
SHATERRED_ARMORY_DAEMON_SCRIPT = 6410
SHATERRED_ARMORY_DAEMON_DIALOG = 6410

MAP_ID_SHATERRED_CITY_SUMBERTON = 5122
SHATERRED_CITY_SUMBERTON = "shattered_city_sumberton"
SHATERRED_CITY_SUMBERTON_DAEMON_ID = "G_1D30A957_9D4F_4279_B92E_1559833A8F55"
SHATERRED_CITY_SUMBERTON_DAEMON_SCRIPT = 6300

MAP_ID_SHATERRED_CITY_MARKET = 5020
SHATERRED_CITY_SUMBERTON_MARKET = "shattered_city_market"
SHATERRED_CITY_SUMBERTON_MARKET_DAEMON_ID = "G_9613C5FB_81B5_40CA_A486_62A5026924A9"
SHATERRED_CITY_SUMBERTON_MARKET_DAEMON_SCRIPT = 6310

MAP_ID_SHATERRED_CITY_INN1 = 5007
SHATERRED_CITY_SUMBERTON_INN1 = "shattered_city_inn1"
SHATERRED_CITY_SUMBERTON_INN1_DAEMON_ID = "G_3C1E0897_80CF_46A9_9AEB_812D4667CE76"
SHATERRED_CITY_SUMBERTON_INN1_DAEMON_SCRIPT = 6320

MAP_ID_SHATERRED_CITY_INN2 = 5008
SHATERRED_CITY_SUMBERTON_INN2 = "shattered_city_inn2"
SHATERRED_CITY_SUMBERTON_INN2_DAEMON_ID = "G_C1808AB9_2D23_4173_A88E_9EC40EBA8E10"
SHATERRED_CITY_SUMBERTON_INN2_DAEMON_SCRIPT = 6330

FACTION_SLAUGHTERGARDE_SPAWN = 73
FACTION_CELESTIAL_ARMY = 74
FACTION_WILDERNESS_HOSTILE = 75
FACTION_WILDERNESS_INDIFFERENT = 76
FACTION_WILDERNESS_HELPFULL = 77
FACTION_WILDERNESS_EVIL = 78
FACTION_WILDERNESS_GOOD = 79
FACTION_WILDERNESS_NAUTRAL = 80

PROTO_QUEST_ITEM_BARREL_OF_SPICE = 12710
PROTO_QUEST_ITEM_MEDALLION = 6750

NAME_QUEST_ITEM_BARREL_OF_SPICE = 5710

QUEST_SPICY_CHICANERY = 1
QUEST_LUMINOSITY = 2
QUEST_PICKING_AT_THE_SCAR = 3
QUEST_MAUG = 4

NAMEID_DOOR_T1_T2 = 901 #{901}{Doors T1-T2}
NAMEID_DOOR_T7 = 907
NAMEID_SHATTERED_TEMPLE_EXIT = 1642 #{1642}{Shattered Temple Exit}
NAMEID_DOOR_T21 = 952

PROTO_DEMON_ARCH_10FT = 136

PROTO_ARMOR_SHIELD_OF_DRAGONRIDER = 6731

GLOBAL_FLAG_VINTRA_ADVANCE = 1 # been paid 100gp up front by Vintra
GLOBAL_FLAG_MAUG_DETECT_EVIL = 2 # cast Detect Evil on maug
GLOBAL_FLAG_MAUG_TOLD_OF_SLAUGHTERGARDE_EXISTS = 3 # Maug tells PCs they are 'in Slaughtergarde', that a piece still exists
GLOBAL_FLAG_LEARNED_OF_EBON_CABAL = 4 # learns of the Ebon Cabal
GLOBAL_FLAG_DEALT_WITH_THE_BARKEEP = 5 # dealt with the barkeep
GLOBAL_FLAG_LEARNED_OF_SLAUGHTERSCAR = 6 # learned of Slaughterscar
GLOBAL_FLAG_TOLD_TO_SPEAK_TO_CHENDREA_ABOUT_SLAUGHTERGARDE = 7 # told to speak to Chendrea about Slaughtergarde
GLOBAL_FLAG_LOOKING_FOR_VINTRA = 8 # looking for Vintra (unused so far)
GLOBAL_FLAG_LEARNED_OF_THE_VARIOUS_RACES = 9 # learned of the various races
GLOBAL_FLAG_QUEST_PROVISIONERS_PAULDRONS = 10 # quest - provisioner's pauldrons
GLOBAL_FLAG_QUEST_ARMOURERS_SAND = 11 # quest - armourer's sand
GLOBAL_FLAG_HAD_THE_MAP_TRANSLATED = 12 # had the map translated
GLOBAL_FLAG_NORBERT_SAYS_TO_SPEAK_TO_THE_HINTERLANDIER = 13 # Norbert says to speak to the Hinterlandier
GLOBAL_FLAG_TEMPLE_COMPLETED = 14 # whatever you need to do in the Temple to win
GLOBAL_FLAG_MAUG_DETECT_MAGIC = 15 # cast Detect Magic on maug
GLOBAL_FLAG_LAB_CLEARED = 16 # killed every Slaughtergarde spawn and friends

GLOBAL_FLAG_MAY_SLEEP_INN = 56 # room flag at Inn (same one as ToEE)

GLOBAL_FLAG_HOWLER_KILLED = 103